Version Display
simpleviewinc/tap-events-force pull request #105
Opened 2020-12-16 21:54 UTC by mpcarolin

## Context / Goal

* to help inform devs on the current version, we should show the version of the tap in the consumer that also links to the release notes

## Updates
* `src/components/meta/versionDisplay.js`
  * created a component that displays the version of the tap
* `src/containers/sessionsContainer.js`
  * updated to display the component if `showVersion` prop is true
* `apps/Sessions.js`
  * passing props down

## Testing
* `keg consumer pack run package=docker.pkg.github.com/simpleviewinc/keg-packages/keg-test-consumer:version-display`
* verify you see the version at the bottom right of the page
* verify you are taken to the release notes when clicking on the version

2020-12-16 23:47 UTC, lancetipton requested changes
Looks great and works well.
I left a pretty long comment about it. Let me know your thoughts.

2020-12-16 23:47 UTC, lancetipton commented on src/components/meta/versionDisplay.js
> +import tapPackage from '../../../package.json'
This is going to include the entire `package.json`. Which can be bad for a number of reasons. 

* A better way would be to do it through ENV's
* We could add a field to the `tap.js` which defines ENVs to be added to the build process, and exposed to the frontend 
  * You could just do it manually in the keg-core webpack config
      * Using either the `DefinePlugin` || `EnvironmentPlugin`
      * This might be a better option because it adds more customization   
      * This would also allow you to create some shortcuts for accessing the `package.json` values
  * Here's a couple example I found online that could be helpful
    * https://alxmrtnz.com/thoughts/2019/03/12/environment-variables-and-workflow-in-expo.html
    * https://docs.expo.io/guides/environment-variables/

  * They would also need to be added to the rollup config using the `plugin-replace`
    * Exactly the same as how we do handle the other envs
    * Only pull in the `tap.js`, and get the ENV list
      * Check if any have a reference to the `package.json`
        * Something like
        ```js
		  {
			// ...other envs to pass on
		    TAP_VERSION: 'package.version',
		    TAP_URL: 'package.homepage'
		  }
		```
      * `package` could be a shortcut to mean the taps `package.json` file
      * Then loop over them and get the values
      * Then add the values to the plugin-replace initialization
      ```js
        // At top of file import the package.json
        import tapPackage from '../../../package.json'

        // In the plugin-replace initialization
        {
          // ...other replace envs
          'process.env.TAP_VERSION': '<tap-version-here>',
          'process.env.TAP_URL': '<tap-url-here>',
        }
      ```
	
* Just make sure the are the same for webpack and rollup
* This would make it much more dynamic, and keep the bundle size down by not including the entire `package.json`

2020-12-18 23:05 UTC, lancetipton approved these changes
Code looks good, and everything worked. 
Thanks

2020-12-21 17:40 UTC, daniel112 approved these changes
all testing passed

2020-12-23 18:47 UTC, merged