Zen 511 session unbook
simpleviewinc/tap-events-force pull request #112
Opened 2021-01-11 20:21 UTC by mpcarolin

**Ticket**: [ZEN-511](https://jira.simpleviewtools.com/browse/zen-511)

## Context

* There is a bug in the booking logic
* If **at the time of initial load**, a session has no capacity remaining, its booking button will be disabled even if there are attendees on the booking/waiting lists that the user set
* Sessions should not be disabled in this scenario so that the user is able to remove them from the booking / waiting lists

## Goal

* Fix the bug

## Updates

* `src/mocks/eventsforce/bookingStates/fullyBooked.js`
  * updated the mock data's "capacity" states so that the attendees are set to be already booked to the session, for testing this scenario
* `src/utils/models/sessions/getDisabled.js`
  * updated the `getDisabled` utility for the booking state factory to ensure that a button is **not** disabled if there are any attendees on the booking or waiting lists.

## Testing
* `keg evf pack run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-511-session-unbook`
1. http://evf-develop.local.kegdev.xyz/?state=fullyBooked.single.stopped
  * in this state, the session is at capacity, but the attendee is not on the booking or waiting list, so it should be disabled
  * verify that the booking button is disabled
2. http://evf-develop.local.kegdev.xyz/?state=fullyBooked.single.stopped
  * in this state, the session is at capacity, but the attendee is on the booking list this time
  * verify that the booking button is enabled, and that you can select it to unbook the attendee
    * after the attendee is unbooked, the button will say "fully booked", but that is expected: in this testing mode, the mock  session capacity doesn't get updated (that's something events force handles)
3. http://evf-develop.local.kegdev.xyz/?state=fullyBooked.group.stopped
  * same as step 1, but now in group-booking mode
  * verify that the booking button is disabled
4. http://evf-develop.local.kegdev.xyz/?state=fullyBooked.group.capacity
  * same as step 3, but now in group-booking mode
  * verify that the booking button is enabled and that you can:  
    * open the modal
    * unbook attendees

2021-01-11 21:33 UTC, daniel112 requested changes
the test cases looks good.
I left a comment on a few things I noticed

2021-01-11 21:33 UTC, daniel112 commented on src/mocks/eventsforce/bookingStates/fullyBooked.js
>            name: 'Mr Frank Smith',
file not related. just marking for comment reference

I see this warning on the console during step 4 testing
- [image](https://user-images.githubusercontent.com/3317835/104239787-4b0ca400-5418-11eb-954a-37689bcb3e9d.png)

to reproduce:
1. http://evf-develop.local.kegdev.xyz/?state=fullyBooked.group.capacity
2. open group booking modal
3. unselect 1 person
4. click `book selected`
5. re-open group booking modal

2021-01-11 21:33 UTC, daniel112 commented on src/utils/models/sessions/getDisabled.js
> +  const hasExistingBookings = bookingList.length || waitingList.length
you may need to update the unit test for this. it's currently failing

[image](https://user-images.githubusercontent.com/3317835/104240755-cd499800-5419-11eb-999c-95876360b6bf.png)

2021-01-12 21:43 UTC, mpcarolin commented on src/mocks/eventsforce/bookingStates/fullyBooked.js
>            name: 'Mr Frank Smith',
This was an issue in `keg-components`. I fixed this here:

https://github.com/simpleviewinc/keg-hub/pull/126

The package is also updated to have that fix synced in.

2021-01-12 21:43 UTC, mpcarolin commented on src/utils/models/sessions/getDisabled.js
> +  const hasExistingBookings = bookingList.length || waitingList.length
Yep, fixed the unit tests and added a few more to test these new cases.

2021-01-13 17:21 UTC, daniel112 approved these changes
looks good

2021-01-15 01:08 UTC, lancetipton approved these changes
Looks good and all tests pass. Thanks

2021-01-15 01:10 UTC, merged