feat: Session List View
simpleviewinc/tap-events-force pull request #114
Opened 2021-01-14 01:41 UTC by lancetipton

**Tickets**
* [ZEN-498](https://jira.simpleviewtools.com/browse/ZEN-498)
* [ZEN-511](https://jira.simpleviewtools.com/browse/ZEN-511)

> **IMPORTANT**
> This PR should be tested along with [this PR](https://github.com/simpleviewinc/keg-hub/pull/105)

[Semver-Status] minor

## Context

We need to update the Sessions Day navigation to match the updated mock-ups
See this ticket => https://jira.simpleviewtools.com/browse/ZEN-472
 

## Goal

* Utilize react-native sectionList
* On Desktop Web show gray line for section titles
* On Mobile show Day number for section titles
* Should also include the name of the day
* On day toggle, it should scroll to the section for that day
* On Desktop web, the day toggle day number needs to be updated when the gray line that separates days touches the bottom of the day toggle component

## Updates
* See this [this PR](https://github.com/simpleviewinc/keg-hub/pull/105)

## Testing
* Run the tests in [this PR](https://github.com/simpleviewinc/keg-hub/pull/105)

2021-01-15 21:31 UTC, mpcarolin reviewed
Code looks great to me, although I left a few non-blocking comments.

All the tests passed and the UI looks like the mock up.

I wanted to leave this video of slightly odd behavior I noticed when double clicking on the day toggle arrows. Sometimes, the day will oscillate between 3 and 2, but it wasn't a huge deal to me: the site behaved as expected and I only noticed this because I was really searching for it.

https://user-images.githubusercontent.com/9517356/104780382-f29e1500-573d-11eb-913d-a12832e7bbfb.mov

I also want to mention that although the mobile UI is **great**, I think the desktop UI's session list is really not intuitive. The removal of the date from the day toggle doesn't make any sense to me and removes context for the user. Furthermore, the lack of dates in the section dividers makes it easy to lose track of which day sessions fall on. Mobile, on the other hand, doesn't have any of these issues. Overall, I really think the desktop UI should change, but everything you did here is exactly up to spec.

2021-01-15 21:31 UTC, mpcarolin commented on src/components/sessions.js
> -)
Having all those components in `sessions.js` has been bothering me. This is so much cleaner now.

2021-01-15 21:31 UTC, mpcarolin commented on src/components/sessionsHeader/sessionsHeader.js
> +  const { currentAgendaDay, agendaLength, isLatestDay, isFirstDay } = agenda
`currentAgendaDay` isn't being used, so we ought to remove this.

2021-01-15 21:31 UTC, mpcarolin commented on src/components/sessionsHeader/sessionsHeader.js
> + * @param {Function} props.onDayChange - function for handling day changes in the day toggle
missing a few jsdocs for props: `agenda`, `currentDay`, and `dayText`, . Also it looks like `styles` isn't actually accepted.

2021-01-15 21:31 UTC, mpcarolin commented on src/components/sessionsList/sessionsDivider.js
> +    mobileSize,
I think this variable would be clearer named as `isMobileSize` or `isMobileWidth`. My first thought when reading `mobileSize` is that it's a number, rather than a boolean.

2021-01-18 17:18 UTC, lancetipton commented on src/components/sessions.js
> -)
Yah, I agree. It may be better to put them all into a folder together actually. Not sure if it makes sense for each one to be it's own folder, but at least they are not all in one file.

2021-01-18 17:18 UTC, lancetipton commented on src/components/sessionsHeader/sessionsHeader.js
> +  const { currentAgendaDay, agendaLength, isLatestDay, isFirstDay } = agenda
updated

2021-01-18 17:18 UTC, lancetipton commented on src/components/sessionsHeader/sessionsHeader.js
> + * @param {Function} props.onDayChange - function for handling day changes in the day toggle
updated

2021-01-18 17:18 UTC, lancetipton commented on src/components/sessionsList/sessionsDivider.js
> +    mobileSize,
updated

2021-01-18 17:19 UTC, lancetipton commented
Made some changes and pushed a new docker container
* Added the date above each section in desktop view. I already spoke with Ben about this and he agreed.

2021-01-18 19:09 UTC, daniel112 approved these changes
Looks good. I ran into some UI related issues that I don't think is a blocker because it's not consistent, but I'll bring it up anyways.

1. there's a bug that seems to only exists on mobile view (web browser), i was not able to reproduce this on mobile view (native browser) 
    - based on the conversation we had earlier, this is tied to the fact that on browser, you 
    - see comment section for more details

**Note:** I don't see this as blocking since on actual devices it works fine.

2021-01-18 19:11 UTC, daniel112 commented on src/components/sessionsList/sessionsList.js
> +export const SessionsList = props => {
1. there's a bug that seems to only exists on mobile view (web browser), i was not able to reproduce this on mobile view (native browser) 
    - based on the conversation we had earlier, this is tied to the fact that on browser, you do a `mouse scroll` whereas on mobile you do a `finger/touch scroll`

* how to reproduce:
   1. load app in browser - mobile view
   2. expand day 1
   3. expand the description. (click `More`)
   4. Scroll down to the point right before you would expect the text to switch to `Day 2 Saturday` AND still see part of the expanded session
       - right about [here](https://user-images.githubusercontent.com/3317835/104954511-9cbbae00-5985-11eb-8320-50c9fde169bf.png)

  5. click the expanded session so it collapses (no session should be expanded at this point)
  6. Scrolling past the label `Day 2 Saturday` will not change the sticky text anymore (bug)

2021-01-18 19:26 UTC, daniel112 requested changes
Almost forgot.
`Eventsforce` wants us to add an ef class on the header component here
- [image](https://user-images.githubusercontent.com/3317835/104955964-616eae80-5988-11eb-888b-bb7b77a812bd.png)

2021-01-18 20:47 UTC, daniel112 approved these changes

2021-01-18 22:18 UTC, mpcarolin approved these changes

2021-01-22 18:17 UTC, merged