update:
simpleviewinc/tap-events-force pull request #120
Opened 2021-02-09 18:13 UTC by daniel112

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-541)

## Context

* EVF changed the behavior of the dayToggle again. there must be no calculated rendering of the day date. It must come directly from the dayName json value for each day.

## Goal

- add prop dayName to agendaDay
- use agendaDay.dayName as the label header instead of calculating it

## Updates

* `src/components/sessionsList/sessionsList.js`
   * update to not calculate dayName but instead use the JSON value
* updated the `AgendaDay` model and style slightly

## Testing

* run `keg evf pack run evf:zen-541-dayname-label`
* navigate to http://evf-zen-541-dayname-label.local.kegdev.xyz/
* Open the JSON editor
* Update the `dayName` properties
    * [image](https://user-images.githubusercontent.com/3317835/107407890-79d57300-6ac7-11eb-8895-5274723bd82a.png)
* hit `Apply Changes`
* verify that the dayToggle text changes based on the current day.dayName
* Verify it truncates when the text is long enough

2021-02-09 20:35 UTC, lancetipton requested changes
Looks good. One thing, looks like a `useMemo` hook should be used.

2021-02-09 20:35 UTC, lancetipton commented on src/components/sessionsList/sessionsList.js
> +const getDayName = (agendaDays = noPropArr, currentDay) => {
seems like this should be a hook, something like `useDayName`, then wrap it in a `useMemo`

2021-02-09 21:20 UTC, daniel112 commented on src/components/sessionsList/sessionsList.js
> +const getDayName = (agendaDays = noPropArr, currentDay) => {
I moved this to `useAgenda` since it's related and gets the store items I need

2021-02-10 16:13 UTC, mpcarolin approved these changes
Looks good to me

2021-02-10 21:37 UTC, lancetipton approved these changes
Looks good, thanks

2021-02-11 19:52 UTC, merged