WIP ZEN-543: Rebuild Workflow
simpleviewinc/tap-events-force pull request #131
Opened 2021-04-30 03:53 UTC by mpcarolin

**Ticket**: [ZEN-543](https://jira.simpleviewtools.com/browse/ZEN-543)

## Context/Goal

* To save developers from a lot of manual, error-prone work, we've decided to make a github action for building and pushing taps repos' docker images when a push to develop is made 

## Updates
* `.github/workflows/imageDeploy.yml`
  * created the workflow that leverages the tap action
* `tap.js`
  * added an alias key to the `tap.js` file, so that you can run `keg tap link` in the evf directory and it will link that alias automatically

## Testing
* verify that this action succeeded: https://github.com/simpleviewinc/tap-events-force/actions/runs/798249626

2021-05-03 18:47 UTC, lancetipton requested changes
Looks good, two small things. Thanks

2021-05-03 18:47 UTC, lancetipton commented on tap.js
> +  alias: 'evf',
Can you move this inside of the `keg` property object.

2021-05-03 18:47 UTC, lancetipton commented on .github/workflows/imageDeploy.yml
> +        token: ${{ secrets.KEG_ADMIN_TOKEN }}
I thought we checked and validated that the `secrets.GITHUB_TOKEN` env works here?

2021-05-05 00:14 UTC, mpcarolin commented on tap.js
> +  alias: 'evf',
updated

2021-05-05 00:17 UTC, mpcarolin commented on .github/workflows/imageDeploy.yml
> +        token: ${{ secrets.KEG_ADMIN_TOKEN }}
That was for `keg-hub`'s workflow.

When I attempted it here, it did not work: 
https://github.com/simpleviewinc/tap-events-force/actions/runs/797803949
* in this example, if you examine the workflow file, the token parameter is omitted, but the action defaults to using `${{github.token}}`

2021-05-19 23:15 UTC, lancetipton approved these changes
Looks good

2021-05-26 23:09 UTC, merged