Zen 626 mobile state label
simpleviewinc/tap-events-force pull request #134
Opened 2021-08-18 16:28 UTC by subaya710

**Ticket**: https://jira.simpleviewtools.com/browse/ZEN-626

## Context

* New UI requirements dictate that state labels appear on the top right of the desktop sessions and also appear for mobile sessions
* Please refer new UI expectations here : https://www.figma.com/file/aLesACdNG3CvInUVuFm4hO/Session-selection---final?node-id=0%3A1

## Goal

* For Desktop : Change state button to appear on the top right rather that bottom right. 
* For Desktop : Ensure price (dollar amount / free etc) that originally existed on the top right is no longer displayed
* For Desktop : When a session is clicked/expanded , the state button now appears on the top right rather bottom right
* For Mobile : Ensure when collapsed a session shows non interactive state label except 'select' and 'read ' on the top right
* For Mobile : Ensure when expanded the state label disappears and existing functionality where state button appears at the bottom of the session remains

## Updates

* keg-hub/taps/tap-events-force/src/components/grid/gridTileContent.js
  * For desktop collapsed view: Deleted the display of price and added the button as a compound element in row 1
* keg-hub/taps/tap-events-force/src/theme/components/grid/gridTileContent.js
  * For desktop collapsed view: Removed styles that were not in use
* keg-hub/taps/tap-events-force/src/components/modals/sessionDetailsModal.js
  *  For desktop expanded view: Deleted the display of price and added the button as a compound element in row 1
* keg-hub/taps/tap-events-force/src/theme/components/modals/sessionDetailsModal.js
  * For desktop collapsed view: Modified styles as required
* keg-hub/taps/tap-events-force/src/components/grid/gridRowContent.js
  * For mobile collapsed and expanded view ensure state labels other that select and read-only appear on top right and disappear when expanded
* keg-hub/taps/tap-events-force/src/theme/components/grid/gridRowContent.js
  * For mobile expanded and collapsed session view , modified styles
* keg-hub/taps/tap-events-force/src/theme/components/grid/gridItem.js
  * Ensuring compound row containing time and state label appear as desired

## Testing

* SetUp
  * Run the command => keg evf pack run evf:zen-626-mobilestatelabel
  * Navigate to http://evf-zen-626-mobilestatelabel.local.keghub.io/

* Test 1 : Desktop collapsed session test
  * Launch events force from the docker image above and navigate to main page indicated in setup
  * Ensure for the session named 'Zerista session day 3' at bottom of page , price is no longer visible and select button is at the top right of the session tile
  * Ensure for session titled 'session at same time other session with presenters and labels' , select button is present at top right of session tile and FREE is no longer displayed
  * Ensure for session titled 'Session on day 2 - limited capacity', the 'on waiting list:1' button is present at the top right
  * Note : since the use case only required changing the placement of the state button (and removing price), testing for other states is not required and the above tests should be sufficient . If however you would like to test other states , please select appropriate data and do so.

* Test 2 : Desktop expanded session test (session modal test)
  * Launch events force from the docker image above and navigate to main page indicated in setup
  * Click on 'Zerista session day 3' session . It should open up a modal. Ensure price is no longer visible and select button is at the top right
  * Click on 'session at same time other session with presenters and labels' . It should open up a modal. Ensure FREE is no longer visible and select button is at the top right
  * Click on 'Session on day 2 - limited capacity' . Ensure the 'on waiting list:1' button is present at the top right

* Test 3 : Mobile sessionexpanded/collapsed test
  * Launch events force from the docker image above and navigate to main page indicated in setup
  * Right click on page and click inspect
  * In the inspector window that opens up , select mobile view on the top left : 'toggle device toolbar'. It should open up the app in a view similar to mobile
  * Ensure for session 'session at same time other session with presenters and labels', there is no state label on top right for the collapsed session tile. When you click it , thereby expanding it , there should be a select button the the bottom
  * Ensure for session titled 'Session on day 2 - limited capacity', the 'On Waiting list' label WITHOUT the number shows up on the top right . When clicked / expanded the state label should disappear and existing functionality with button showing 'On waiting list : 1 ' should become visible

2021-08-18 21:46 UTC, mpcarolin requested changes
Functionality and styles all looked good 👍 . I just have a few code recommendations

2021-08-18 21:46 UTC, mpcarolin commented on src/components/grid/gridRowContent.js
> +  const attendees = useStoreItems('attendees')
I would just add a comment explaining why this function is memoized based on attendees: because the session state only gets updated when bookings are modified (attendees changed in some way). The session object itself keeps the same reference, so we can't use that as the only memo dependency.

2021-08-18 21:46 UTC, mpcarolin commented on src/components/grid/gridRowContent.js
> +}
Hmm, our eslinter doesn't seem to be working on the commits. Can you add some spaces here? Sorry, I know it's very minor but consistency is always nice

```suggestion
const useSessionState = (session) => {
  const attendees = useStoreItems('attendees')
  return useMemo(() => getBookingState(session), [session, attendees])
}
```

2021-08-18 21:46 UTC, mpcarolin commented on src/components/grid/gridRowContent.js
> +  if (sessionState == SESSION_BOOKING_STATES.SELECT || sessionState == SESSION_BOOKING_STATES.READ_ONLY) { labelToDisplay = ''}
you can do the same logic in a simpler and functional way like this:

```suggestion
  const labelToDisplay = (sessionState === SESSION_BOOKING_STATES.SELECT || sessionState === SESSION_BOOKING_STATES.READ_ONLY)
    ? ''
    : sessionState
```

* also I changed boolean expression to use the strict-equality operator `===`. We prefer that over the abstract equality operator, `==`, which is more complex. `==` does type coercion first, then checks for equality. This requires the reader to know the type coercion tables which are long and not very intuitive. It's also inconsistent with every other programming language in the world, so even though `==` works just fine here, I think it's just better we stick with `===` for consistency and clarity.

This mdn doc is useful: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness

2021-08-19 16:18 UTC, lancetipton requested changes
Overall looks good. I have a couple recommendations that I added comments for. 

Thanks

2021-08-19 16:18 UTC, lancetipton commented on src/components/grid/gridRowContent.js
> +}
I'm pretty sure the linter doesn't run until it's merged.
Otherwise, any changes it made would have to be commited to the PR branch
Which means, the remote PR branch would now be 1 commit ahead of your local.
So you would have to remember to pull down the changes every time you made an update to the code locally.

That said, I'm pretty sure this spacing would be fixed by the linter, once the code is merged upstream

2021-08-19 23:12 UTC, subaya710 commented on src/components/grid/gridRowContent.js
> +  const attendees = useStoreItems('attendees')
Done . Added to the stateLabel.js file

2021-08-19 23:14 UTC, subaya710 commented on src/components/grid/gridRowContent.js
> +}
Made changes anyway.Now in stateLabel file. However, Would you like me to leave this in without spaces and verify if it is formatted correctly when merged?

2021-08-19 23:15 UTC, subaya710 commented on src/components/grid/gridRowContent.js
> +  if (sessionState == SESSION_BOOKING_STATES.SELECT || sessionState == SESSION_BOOKING_STATES.READ_ONLY) { labelToDisplay = ''}
Done . And duly noted . I have read a lot of comments about this online as well. DA for me for using ==. Thanks

2021-08-19 23:18 UTC, subaya710 commented on src/components/modals/sessionDetailsModal.js
> +      Footer={ null
Done. Added Jira ticket number

2021-08-19 23:30 UTC, subaya710 commented on src/theme/components/grid/gridRowContent.js
> +        color: colors.primary
Duly noted . This has been moved to StateLabel theme, but i have only used shortcuts there

2021-08-19 23:31 UTC, subaya710 commented on src/theme/components/modals/sessionDetailsModal.js
> +          flexDirection: 'row',
Done

2021-08-19 23:35 UTC, subaya710 commented on src/theme/components/grid/gridRowContent.js
> +        mT: 13,
I agree . In this case i have used retheme and it has been moved to StateLabel. However , this issue i see exists in multiple places of the code base and i'm wondering rather than make one update , if we should make a ticket to standardize such styles throughout this code base.

2021-08-19 23:40 UTC, subaya710 commented on src/components/modals/sessionDetailsModal.js
> +            { formatSessionDateTime(
I did not touch this piece of code since its not in the requirement for this ticket. However , i do agree with your suggestion. We do have another ticket dealing with the modifications to time piece and it would be good to handle it there . I have this suggestion noted. Would you agree?

2021-08-19 23:42 UTC, subaya710 commented on src/components/grid/gridRowContent.js
> +          { !(isOpen) && (
Thanks . I usually don't do that . I believe i started with a compound logic and then narrowed it down to just 'isOpen' and forgot about those braces. Good catch

2021-08-19 23:42 UTC, subaya710 commented on src/components/grid/gridRowContent.js
> +            style={theme.get('gridItem.sessionTime.main')}
Done. Thanks for the info. Will use UseStyle next time for the get functionality

2021-08-20 17:22 UTC, mpcarolin approved these changes
Looks good. Although, please delete `src/theme/stateLabel.js` before you merge, if you're no longer using it.

2021-08-20 17:22 UTC, mpcarolin commented on src/theme/components/stateLabel.js
> +}
I believe you can delete this file now, since you're now using `reStyle` for all these styles.

2021-08-23 18:00 UTC, lancetipton requested changes
Looks good. There's a few minor items that need updated. Let me know if you have questions

2021-08-23 18:00 UTC, lancetipton commented on src/components/grid/gridRowContent.js
> +            style =  {useStyle('gridItem.sessionTime.main')}
Hooks should not be called inline with the components props
Set the response from the hook to a `const`, then pass it as a `prop`
```js
         const sessionTimeStyle = useStyle('gridItem.sessionTime.main')
         //...other codes
          <SessionTime
            style={sessionTimeStyle}
            start={session.startDateTimeLocal}
            end={session.endDateTimeLocal}
            military={militaryTime}
          />
```

2021-08-23 18:00 UTC, lancetipton commented on src/components/grid/gridRowContent.js
> +import React, { useState, useCallback, useMemo } from 'react'
Why was `useMemo` added to this file?
It's not being used anywhere, it should be removed

2021-08-23 18:00 UTC, lancetipton commented on src/theme/components/stateLabel.js
> +}
+1

2021-08-23 19:11 UTC, subaya710 commented on src/components/grid/gridRowContent.js
> +            style =  {useStyle('gridItem.sessionTime.main')}
Done , Also changed rowContentStyle to use getStyle instead of theme.get

2021-08-23 19:12 UTC, subaya710 commented on src/components/grid/gridRowContent.js
> +import React, { useState, useCallback, useMemo } from 'react'
Missed that. Apologies

2021-08-23 22:51 UTC, lancetipton requested changes
Looks good. Thanks for doing the updates. I ran through the test once more, and found a small item related to the icon.
The icon's top and bottom get clipped due to the parent not allowing overflow
See this image here => https://i.imgur.com/DzYkkWg.png

2021-08-25 00:37 UTC, lancetipton approved these changes
Looks good, thanks

2021-08-25 00:39 UTC, merged