ZEN-634: Moved Labels
simpleviewinc/tap-events-force pull request #137
Opened 2021-08-25 00:20 UTC by mpcarolin

**Ticket**: [ZEN-634](https://jira.simpleviewtools.com/browse/ZEN-634)

> Note: I integrated with Subaya's changes from `ZEN-626`, so that PR should be merged into develop before this is reviewed

## Goal
* update the location of the labels to anchor to the bottom of the session item
* add a divider between the labels and the other components of the session item

## Updates
* `src/components/grid/gridItem.js`
  * removed unused list styles
* `src/components/grid/gridTileContent.js`
  * Added the labels divider component
  * Moved the labels component to the bottom of the children, so that labels now appear last
  * Changed the order of the component *definitions* to match our usual conventions (defined before called)
* `src/theme/components/grid/gridTileContent.js`
  * updated styles of presenters to fill the session item view, pushing labels to bottom
* `.devcontainer/Dockerfile` & `.devcontainer/devcontainer.json`
  * configured codespaces to automatically run `yarn install` on initialization
  * we can just remove this later if we end up ditching codespaces

## Testing

* [Start a codespace to review this branch](https://docs.github.com/en/codespaces/developing-in-codespaces/using-codespaces-for-pull-requests#reviewing-a-pull-request-in-codespaces)
* `yarn web`
* For desktop session items, verify that:
  * the labels appear at the bottom of each session tile
  * there is a divider between the labels and the rest of the item
  * the labels anchor to the bottom of the session item
    * the ticket says the opposite, but I'm 99% sure it's wrong -- the mockups have each list anchored to the bottom 
  * it matches the figma mock's stytes: https://www.figma.com/file/aLesACdNG3CvInUVuFm4hO/Session-selection---final?node-id=0%3A1
* This does not affect mobile web, so no testing is needed there

2021-08-25 00:50 UTC, mpcarolin commented on src/components/grid/gridTileContent.js
> +})
These are not new changes. I just moved these above the gridTileContent component to conform to our ordering conventions.

2021-08-25 00:50 UTC, mpcarolin commented on src/components/grid/gridTileContent.js
> +      { Boolean(labels?.length) && <LabelsDivider className='ef-session-labels-divider' /> }
I made up this class name, but it may have to change if they have a different class in mind

2021-08-25 00:51 UTC, mpcarolin commented on src/components/grid/gridTileContent.js
> +      />
Not new code. This is just moved to the bottom of the children

2021-08-25 16:15 UTC, lancetipton requested changes
Code looks good. I made a few comments about the theme files
Also, `yarn install` did not run for me in the code-space => https://i.imgur.com/lpU5dN7.png
The UI looks good. Thanks

2021-08-25 16:15 UTC, lancetipton commented on src/theme/components/grid/gridTileContent.js
> +      flexGrow: 1,
Can you do me a favor and start converting these to shortcuts where possiable.
1. It makes the bundle smaller, little bit by bit
2. It will make it more consistent with the newer theme files we have added

2021-08-25 16:15 UTC, lancetipton commented on src/theme/components/grid/gridItem.js
> +        flex: 1,
See other comment about shortcuts

2021-09-02 00:02 UTC, subaya710 approved these changes
Approved

2021-09-02 00:02 UTC, mpcarolin commented on src/theme/components/grid/gridTileContent.js
> +      flexGrow: 1,
Yep, updated

2021-09-02 00:03 UTC, mpcarolin commented on src/theme/components/grid/gridItem.js
> +        flex: 1,
Updated

2021-09-08 23:50 UTC, lancetipton approved these changes
Looks good.
Just one minor thing that may not be a blocker, so I'm going to approve, but please validate it's correct before merging.

Thanks

2021-09-08 23:50 UTC, lancetipton commented on src/components/grid/gridTileContent.js
> +  bBC: theme.colors.dimTextGray,
This color doesn't match the mockup color => https://i.imgur.com/AGeTfQo.png

Not sure if this is something we need to worry about or not as the EU team is handling most of the color styles.

But I figured it's worth bringing up in case this is one we are handling

2021-09-10 00:25 UTC, mpcarolin commented on src/components/grid/gridTileContent.js
> +  bBC: theme.colors.dimTextGray,
Updated

2021-09-10 00:25 UTC, merged