Zen 627 session details modal updates
simpleviewinc/tap-events-force pull request #139
Opened 2021-09-01 21:06 UTC by mpcarolin

**Ticket**: [ZEN-627](https://jira.simpleviewtools.com/browse/zen-627)

> NOTE: [This ReTheme PR](https://github.com/simpleviewinc/keg-hub/pull/199) needs to be merged and deployed prior to merging in this PR.

## Goal

* Update session details modal layout and positionining styles
* Do some refactoring with `reStyle`

## Updates

* `src/components/modals/session/sessionDetails.js`
  * Renamed the `Body` component to `SessionDetails` and extracted it to its own file
  * Updated styles mentioned in the ticket to match mockup
* `src/components/modals/session/sessionDetailsHeader.js`
  * Extracted header to its own file
  * Updated styles mentioned in the ticket to match mockup
* `src/components/modals/session/sessionDetailsModal.js`
  * just moved this under a `session` folder, within `modals`
* `src/components/sessionDetails/sessionPresenters.js`
  * Simplified
    * Replace `useStyle` with `reStyle` and removed associated theme file styles
    * Removed unused style prop
* `src/constants/values.js`
  * Moved `DISPLAY_PROPERTIES` to `EVF_CATEGORIES`
    * it was previously incorrectly placed under `INTERNAL_CATEGORIES`, which meant it wasn't being read from the root props. This was causing a bug (that went unnoticed) which prevented the Sessions component consumer from changed display properties
* `src/mocks/eventsforce/evfModalBuilder.js`
  * updated the modal to use the `large` size so that we can actually see content properly
* `src/theme/components/modals/sessionDetailsModal.js`
  * removed unused styles (now provided by `reStyle`)

## Testing
* `keg evf pack run package=evf:zen-627-session-details-modal-updates`
  * This runs this branch, with the latest reStyle changes synced in from [this PR](https://github.com/simpleviewinc/keg-hub/pull/199)
* Open up any session details modal
* Verify that the styles match the figma mockup: https://www.figma.com/file/aLesACdNG3CvInUVuFm4hO/Session-selection---final?node-id=0%3A1
* Note that I only focused on updating the features listed in the ticket: 
    * Move the header title down
    * Add vertical divider between time and day-name
    * Ensure there are dividers between description, labels, and top section
    * Move labels to the bottom
    * Move select button to top-right
* Other style updates are handled in other tickets

2021-09-03 21:35 UTC, subaya710 approved these changes

2021-09-09 00:13 UTC, lancetipton requested changes
Overall looks good, but there's a few minor things to look at. Let me know if you have questions. Thanks

2021-09-09 00:13 UTC, lancetipton commented on src/components/modals/session/sessionDetailsModal.js
> +export const SessionDetailsModal = ({ session, visible, labels }) => {
Not sure where else to put this, but the space around the modal does not match the mock-ups.
That said, I'm pretty sure that's something the EU team handels. So it may be a non-issue

https://i.imgur.com/i2ysmHx.png

2021-09-09 00:13 UTC, lancetipton commented on src/components/modals/session/sessionDetails.js
> +  bBC: theme.colors.dimTextGray,
Same as in PR #137
This color should be `#DDDDDD` according to the mockups
Tap-EVF => https://i.imgur.com/7HhcBki.png
Mock-up => https://i.imgur.com/16o38lR.png

2021-09-09 00:13 UTC, lancetipton commented on src/mocks/eventsforce/evfModalBuilder.js
> +const Modal = RSModal
I am very confused by this. What's the point of this change?

2021-09-09 00:13 UTC, lancetipton commented on src/theme/components/modals/sessionDetailsModal.js
> +          marginTop: -5,
Can you make this a shortcut => `mT: -5`

2021-09-09 22:11 UTC, mpcarolin commented on src/components/modals/session/sessionDetailsHeader.js
> +  alignSelf: 'center',
Done

2021-09-09 22:12 UTC, mpcarolin commented on src/components/modals/session/sessionDetailsHeader.js
> +const Title = reStyle(Text)({
Really I wanted to do `reStyle(Subtitle)`, but this is a case of that class specificity issue we discussed.

2021-09-09 22:12 UTC, mpcarolin commented on src/components/modals/session/sessionDetailsHeader.js
> + const ActionButton = ({ session }) => {
Done

2021-09-09 22:41 UTC, mpcarolin commented on src/components/modals/session/sessionDetailsModal.js
> +export const SessionDetailsModal = ({ session, visible, labels }) => {
As discussed, the bootstrap modal itself adds some padding, and I assume EventsForce  add their own as well, so I removed unneeded horizontal padding.

2021-09-09 22:41 UTC, mpcarolin commented on src/components/modals/session/sessionDetails.js
> +  bBC: theme.colors.dimTextGray,
Updated

2021-09-09 22:41 UTC, mpcarolin commented on src/mocks/eventsforce/evfModalBuilder.js
> +const Modal = RSModal
I meant to remove this. Updated

2021-09-09 22:42 UTC, mpcarolin commented on src/theme/components/modals/sessionDetailsModal.js
> +          marginTop: -5,
Updated (also updated a few more)

2021-09-10 23:07 UTC, lancetipton approved these changes
Looks good. Just left one comment, but it's not a blocker

2021-09-10 23:07 UTC, lancetipton commented on src/components/modals/session/sessionDetailsHeader.js
> +const Title = reStyle(Text)({
I get that, but until then, deepMerge would still be cleaner. To me this looks better, and is to quickly understand
```js
const Title = reStyle(Text)(
  deepMerge(
    TitleStyles,
    { $xsmall: { mB: 6 }, $small: { mB: 10, ftSz: 20 } }
  )
)
``` 

But it's not a big deal, so if you don't want to change don't worry about it

2021-09-14 22:52 UTC, merged