Zen 629 price in select
simpleviewinc/tap-events-force pull request #152
Opened 2021-10-21 19:46 UTC by subaya710

**Ticket**: https://jira.simpleviewtools.com/browse/ZEN-629

## Context

To change the behavior of the price functionality 

## Goal

* Ensure the app matches templates as provided in https://www.figma.com/file/aLesACdNG3CvInUVuFm4hO/Session-selection---final
* Ensure price is available in the select button

## Updates

* Updated BookingButton.js to ensure text and price is displayed according to the rules :
 a. If the session has a price and is a SELECT state, the text displayed should change to BUY.
 b. If the session does not have a price and is a SELECT state, the text displayed should remain SELECT.
 c. If there is no cost , the button should not display any price or alt text like FREE
 d. If a session has a price but is ANY other state (e.g WAITING_LIST) no price should be displayed

## Testing

* Setup
  * Run the command => keg evf pack run evf:zen-629-priceinselect
  * Navigate to http://evf-ZEN-629-PriceInSelect.local.keghub.io
  Note : The current default test data should be enough to validate this ticket

* Testing all requirements
  * Ensure that for a select session with a price , the text on the button appears as 'BUY <price>'. 
  e.g : BUY $923
  * Ensure that for a select session without a price , the text on the button appears as just 'SELECT'
  * Ensure no FREE label appears anywhere for any state
  * Ensure for a waiting list , even though it has a price , no price is displayed . i.e. text should only be 'WAITING LIST' regardless of whether the session has a price or not

2021-11-08 22:37 UTC, mpcarolin requested changes
Just setting this to request-changes for the planned integration test

2021-11-30 21:41 UTC, subaya710 commented
> Just setting this to request-changes for the planned integration test

Hey Michael . Integration tests have been added . Please reference just the src/components/__tests__/bookingButton.integration.js file for your review since that was the only one updated since your last review. Thanks

2021-11-30 22:18 UTC, mpcarolin requested changes
Hey it's looking good. These tests are SUPER helpful. They tell me how the booking button is supposed to behave, which I never had memorized.

I just have a few minor recommendations, mostly with naming.

2021-11-30 22:18 UTC, mpcarolin commented on src/components/__tests__/bookingButton.integration.js
> +describe('Booking button with price integration test', () => {
I would just name this test "Booking button". The "integration" part is already implied via the file name.

2021-11-30 22:18 UTC, mpcarolin commented on src/mocks/eventsforce/testDataBookingButton/activeSessionWithPrice.js
> +}
Most of this is just duplicating the existing `testData.json` file's content. It would be better to do:
```js
import testData from 'SVEvfMocks/eventsforce/testData.js'

export default {
  ...testData,
 sessions: [
    {
      allowBooking: true,
      identifier: '0',
      name: 'Session Title',
      summary: 'Test summary',
      dayNumber: 1,
      startDateTimeLocal: '2020-08-03 09:00:00',
      endDateTimeLocal: '2020-08-03 13:30:00',
      presenterIdentifiers: [ '1', '2' ],
      labelIdentifiers: [ '1', '2', '3', '4' ],
      locationIdentifier: '1',
      liveVideoUrl: 'https://us02web.zoom.us/j/1234',
      recordedVideoUrl: 'https://www.youtube.com/watch?v=21X5lGlDOfg',
      restrictToAttendeeCategories: [],
      capacity: {
        isUnlimited: true,
      },
      price: {
        currency: 'USD',
        amount: 923.0,
      },
    },
  ],

```
(also note that I just made the "summary" field shorter, to be less noisy)

This is a lot cleaner I think, and if we ever need to change the `testData.json` contents, these tests will receive those updates.

2021-11-30 22:18 UTC, mpcarolin commented on src/mocks/eventsforce/testDataBookingButton/activeSessionWithPrice.js
> +}
also, you can just name the folder "bookingButton", because all of the data in `mocks/eventsforce` is testData, so it's implied.

2021-11-30 22:18 UTC, mpcarolin commented on src/components/__tests__/bookingButton.integration.js
> +  it('For an active session with price and NO waiting list : Should have state displaying BUY with price present', async () => {
For each of these tests, it would be clearer to follow the jest conventions and use the `it('should <assertion>)` format for test names.

For example:
```js
  it('should display BUY <PRICE>, for active sessions with price and no waiting list', async () => {
```

2021-12-01 03:47 UTC, subaya710 commented on src/components/__tests__/bookingButton.integration.js
> +describe('Booking button with price integration test', () => {
Done

2021-12-01 03:47 UTC, subaya710 commented on src/mocks/eventsforce/testDataBookingButton/activeSessionWithPrice.js
> +}
Done , Great suggestion!

2021-12-01 03:48 UTC, subaya710 commented on src/components/__tests__/bookingButton.integration.js
> +  it('For an active session with price and NO waiting list : Should have state displaying BUY with price present', async () => {
Done

2021-12-01 16:23 UTC, mpcarolin approved these changes
Looks good. Thank you!

2022-01-03 23:54 UTC, merged