Zen 355 styles fixes
simpleviewinc/tap-events-force pull request #57
Opened 2020-09-23 04:49 UTC by lancetipton

**Ticket [ZEN-355](https://jira.simpleviewtools.com/browse/ZEN-355)** 

> **Notes**
> This PR is directly tied to [this PR](https://github.com/simpleviewinc/keg-hub/pull/38)
>   * They should be merged at the same time
>
> Originally this ticket was to add a `react-helmet`
>   * I could not get that library to not de-dupe styles that were already added
>   * I knew it had to be possible, so I wrote it myself
>
> Because of this, the jira ticket and this pull request don't really line up
>   * This should be the last styling change ticket. At least I hope it is
>   * I'm tired of dealing with it

### [Semver Status] major

## Context
* Events-Force is defining their styles in CSS
* Their clients can define custom CSS as well
* Currently, the tap, using re-theme, is only compatible with JSON style objects
* We need to be able to pull styles from stylesheets already applied to the DOM and apply them to keg-components

## Goal
* Use the already added className prop, to allow applying styles useing the dom
  * This should only happend when in a web context
  * Native context, the style attribute should still be used
  * Ensure no changes need to be added to taps when defining styles
  * Ensure styles are not duplicated on the Dom
    * This is gold right here. I can't find any other repo that does this
    * It puts ReTheme on another level in my opinion 
* Taps can now do the following
  * Use `.css` styles applied to the dom and classNames **(web only)**
  * Use the style attribute, and still get all the benefits of the Dom
    * This works cross-platform

## Updates
* `package.json`
  * Fixed issue with start command
* `src/assets/icons/evf/elements/dayToggleLeft.js` && `src/assets/icons/evf/elements/dayToggleRight.js`
  * Clean up a little bit
  * Added memo hook
* `src/components/dates/dayToggle.js`
  * Fixed some styling issues
    * Updated to use `styles` instead of `style`
* `src/components/dates/updateDayButton.js`
  * Cleaned up styles
* `src/components/sessions.js`
  * Added ScrollView from `Keg-Components`
* `src/containers/gridContainer.js`
  * Added `?` on style paths
* `src/containers/rootContainer.js`
  * Added direct import of `sessionsContainer`
    * Was causing issues with mobile
* `src/theme/components/button/*`
  * **Most of these changes are to fix styling on mobile**
* `src/theme/dynamicClassMap.js`
  * Cleaned up a number issues with style sheet parsing
  * Updated to work with changes made to `ReTheme`
* `./tap.js`
  * Building on mobile throws errors when using `const path = require('path')`
  * Updated to use relative paths based on the packager

## Testing

> **Notes**
> This is the same tests as [this PR](https://github.com/simpleviewinc/keg-hub/pull/38)
> So if you already did the tests for that one, they you have test this one

* Run Docker package => `keg evf pack run docker.pkg.github.com/simpleviewinc/keg-packages/tap:keg-mobile-build`
  * Ensure it runs
  * Open the inspector and check out the `Dom Tree`
    * Styles should no longer be applied to the elements with the style attribute
      * [All View / Text components should be using a class](http://snpy.in/MwwBpH)
      * [Some will still have styles ( Animated elements / Some primitives )](http://snpy.in/TuQOGY)
      * [Some will have buttons and styles for animations (buttons)](http://snpy.in/3d2mAV)
* Test Docker package => `keg evf pack run docker.pkg.github.com/simpleviewinc/keg-packages/tap:keg-mobile-build test`
  * Ensure all tests pass

2020-09-23 19:16 UTC, mpcarolin approved these changes
Passed testing and looks good to me. Added one non-blocking suggestion.

Still reviewing the other PR.

2020-09-23 19:16 UTC, mpcarolin commented on tap.js
> +  : '../..'
can you add a comment explaining why this is necessary? Sounds like it has something to do with Metro?

2020-09-23 22:32 UTC, daniel112 requested changes
looks good. just found 1 minor thing with the evfButton color

2020-09-23 22:32 UTC, daniel112 commented on src/theme/components/button/evfButton.js
> +    $web: {
marking this file for reference.
The  `Default` EvfButton is not getting the right background color (it's getting all the other styles correctly)
it should be using the color that is defined in `.ef-button-default` (#525859) but it's instead using the keg-components default color

![image](https://user-images.githubusercontent.com/3317835/94076301-9c355100-fdb1-11ea-99cf-3221db5bbbfc.png)

2020-09-24 03:55 UTC, lancetipton commented on tap.js
> +  : '../..'
Yah, metro was throwing because you can't import node core modules in a react native file. This file gets imported into one of the containers. I think it's rootContainer.
I'l add a comment.

2020-09-24 04:18 UTC, lancetipton commented on src/theme/components/button/evfButton.js
> +    $web: {
This is fixed. The code to set the correct color was commented out. I added it back it, and it's working properly now

2020-09-24 04:19 UTC, lancetipton commented on tap.js
> +  : '../..'
Updated with some comments

2020-09-24 04:21 UTC, lancetipton commented
Fixed some minor issues brought on in the PR reviews. Also pushed new docker package. It's ready for review again

2020-09-24 15:35 UTC, lancetipton commented on src/theme/components/button/evfButton.js
> +    $web: {
This is fixed

2020-09-24 16:30 UTC, daniel112 approved these changes
looks good!

2020-09-24 22:29 UTC, merged