Zen 363 loading btn
simpleviewinc/tap-events-force pull request #58
Opened 2020-09-23 23:40 UTC by daniel112

> Note: depends on https://github.com/simpleviewinc/keg-hub/pull/37

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-363)

## Context

* we need to be able to indicate to the user that we're loading/processing something after a button action
* evf guys mentioned that their app uses font awesome spinner. (FontAwesome 4 spinner to be exact)
* The `Processing` button should have:
   * loading indicator on the left
   * text "Processing" on the right

## Goal

* Update the `EvfButton` for a new prop `isProcessing`
* when `isProcessing` is true, change the content to a custom Processing component 

## Updates

* `src/assets/icons/evf/elements/loading.js`
   * added fontAwesome 4 spinner as SVG Component

* `src/components/button/evfButton.js`
   * Updated for new prop `isProcessing`
   * added `Processing` component which contains the spinner and text

* `src/components/loading/evfLoading.js`
  * Custom Loading component

* `src/containers/testContainer.js`
  * added examples of the evfButtons

* `src/theme/components/modals/groupBookingModal.js`
   * styling update on the bottom section
## Testing

* TBA

2020-09-30 21:31 UTC, mpcarolin requested changes
Hey, overall looks really good and passed testing.

It just needs to be rebased with `develop`. I also provided some suggestions in my comments.

2020-09-30 21:31 UTC, mpcarolin commented on src/components/button/evfButton.js
> +    main: {
looks like this could just be `main: fitWidth`

2020-09-30 21:31 UTC, mpcarolin commented on src/components/button/evfButton.js
> +const Processing = ({ styles, size }) => {
can you add a prop for the processing text here and in `EvfButton`? It could default to `Processing`, but we might need to override that at some point

2020-09-30 21:31 UTC, mpcarolin commented on src/components/loading/evfLoading.js
> +const CustomIndicator = ({ size, styles }) => {
this is great.

I actually think it could go into `keg-components` as a generic `SpinIndicator` or something. Then you just pass in your icon and now we have a rotating spinner for any icon. 

Just a suggestion, though. We could wait until another use case comes up

2020-09-30 21:39 UTC, lancetipton requested changes
Looks really good. I like how you did the loading. Just a few things to look at.

2020-09-30 21:39 UTC, lancetipton commented on src/assets/icons/evf/elements/loading.js
> +import * as React from 'react'
Any reason this doesn't use the [SvgIcon from keg-components](https://github.com/simpleviewinc/keg-hub/blob/develop/repos/keg-components/src/assets/icons/svgIcon/svgIcon.js)

2020-09-30 21:39 UTC, lancetipton commented on src/components/button/evfButton.js
> +    minWidth: 'fit-content',
The `fit-content` rule does not work for react-native. As a work around on I've been using =>
```js
    flexDirection: 'row',
    alignSelf: 'flex-start',
```
* This works for in the theme, as we can separate between native / web.
* But we can't do that here, when it's inline.
* Can you try using the above two rules instead of ` minWidth: 'fit-content',`
* I'm pretty sure we should be able to swap the above rules in for all instance of `fit-content` in the theme too. I just never tested it.

* For now, if it works, just do it for this since it's defined inline, and we can't use the $native / $web

2020-09-30 21:39 UTC, lancetipton commented on src/components/loading/evfLoading.js
> +import React from 'react'
This is dope. Nice reuse of KegLoading.

2020-09-30 21:39 UTC, lancetipton commented on src/theme/components/modals/groupBookingModal.js
> +              width: 'fit-content',
I mentioned it in an above comment, but `fit-content` only works for web.
You should be able to replace it with =>
```js
    flexDirection: 'row',
    alignSelf: 'flex-start',
```

2020-09-30 22:06 UTC, daniel112 commented on src/components/button/evfButton.js
> +    main: {
fitWidth can be null/undefined.
in which case I don't actually want to set `main` as null/undefined (it causes style issues)

2020-09-30 22:08 UTC, daniel112 commented on src/components/button/evfButton.js
> +const Processing = ({ styles, size }) => {
can do

2020-09-30 22:15 UTC, daniel112 commented on src/components/loading/evfLoading.js
> +const CustomIndicator = ({ size, styles }) => {
i can see that. but the custom Indicator is directly tied to `KegLoading` so its not really that generic. 
and the animation hook is already accessible from `keg-components` so there's really not much other work that a consumer needs to do to use a custom icon.
but i do like the idea of being able to just pass in an Icon to the component and it would use that. someday

2020-09-30 22:20 UTC, daniel112 commented on src/assets/icons/evf/elements/loading.js
> +import * as React from 'react'
I thought about using `SvgIcon` but 
I just wanted to keep it consistent with the way the other svg elements are being loaded.
Since we previously had a custom component `EVFIcons` with its own sets of props. I ended up following that route


maybe that's a cleanup item we can do afterwards. update all the icons in `icons/evf/elements` to use SvgIcon instead

2020-09-30 22:27 UTC, daniel112 commented on src/theme/components/modals/groupBookingModal.js
> +              width: 'fit-content',
that doesnt seem to work. but i also already have flexDirection and alignSelf set to some value. 
```Javascript
// original obj
$xsmall: {
              flexDirection: 'row',
              alignSelf: 'flex-end',
              paddingTop: 26,
              paddingBottom: 35,
              flex: 1,
              width: 'fit-content',
            },
```
but also. it doesn't seem like i need the `width: 'fit-content` in here. so i can just remove it from the theme

2020-09-30 22:28 UTC, daniel112 commented on src/components/button/evfButton.js
> +    minWidth: 'fit-content',
swapping the `minWidth: 'fit-content` doesnt seem to work. its styled the same as if I didn't pass anything in

2020-09-30 22:44 UTC, lancetipton commented on src/assets/icons/evf/elements/loading.js
> +import * as React from 'react'
If the plan is to eventually merge them all over to `SvgIcon`, then all new code should just use it. No point in creating extra work for ourselves later. Let's just do it now, and update the others later when we have the time.

2020-09-30 22:46 UTC, lancetipton commented on src/components/button/evfButton.js
> +    minWidth: 'fit-content',
Try also adding `minWidth: "100%"`. This case is different then others where `fit-content` was on the `width` rule. Because it's `minWidth`, Adding the `100%` might do the trick

2020-09-30 22:46 UTC, lancetipton commented on src/theme/components/modals/groupBookingModal.js
> +              width: 'fit-content',
works for me

2020-09-30 22:46 UTC, daniel112 commented on src/assets/icons/evf/elements/loading.js
> +import * as React from 'react'
yeah, u right. will update this

2020-09-30 22:49 UTC, mpcarolin commented on src/components/loading/evfLoading.js
> +const CustomIndicator = ({ size, styles }) => {
Sounds good.

But my main point is just that it's a fairly common use case to need an icon to spin indefinitely. So much so that FontAwesome [created a class](https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons) just for that. 

That part could be generic. So rather than just repeat this animation wrapper for every one, I think it would make sense down the line to do something like:

```js
const spinners = {
  foo: Spinner(Icons.Foo),
  bar: Spinner(Icons.Bar),
  ...
}
```

if and only if we have more icons to make into spinners of course

2020-09-30 22:50 UTC, mpcarolin commented on src/components/button/evfButton.js
> +    main: {
ah gotcha

2020-09-30 22:55 UTC, lancetipton requested changes
Just one comment. The rest looks good

2020-09-30 22:55 UTC, lancetipton commented on src/components/button/evfButton.js
> +    minWidth: 'fit-content',
It the above doesn't work. Just add it to the theme in `theme/components/button/evfButton.js` after the `primary` key
Something like this in the evfButton theme file => 
```js
primary: {
  ...
},
processing: {
  main: {
    $web: { minWidth: 'fit-content },
  }
}

```

Then in this file you can reference it in the theme.get call on line 27 =>
```js
  return theme.get(
     btnStyles,
     custom.styles,
      theme?.button?.evfButton?.processing,
     // ...other codes
  }

```

2020-09-30 23:13 UTC, daniel112 commented on src/components/button/evfButton.js
> +    minWidth: 'fit-content',
I moved this to the evfButton theme instead so we can separate by $web and $native

2020-09-30 23:14 UTC, daniel112 commented on src/components/loading/evfLoading.js
> +const CustomIndicator = ({ size, styles }) => {
gotcha. yeah i dig it

2020-09-30 23:43 UTC, lancetipton approved these changes
Looks good, just one small suggestion, but it's not blocking

2020-09-30 23:43 UTC, lancetipton commented on src/theme/components/button/evfButton.js
> +    disabled: {
So looking at this file all these states could be cleaned up like this => 
```js
const buildButtonState = stateStyles => deepMerge({
  main: {
    $all: {
      flex: 1,
      justifyContent: 'center',
      borderRadius: 0,
      padding: 0,
    },
    $web: {
      boxShadow: '0px 1px 1px rgba(0, 0, 0, 0.15)',
    },
  },
  content: defaultTextStyle,
}, stateStyles)


const buttonStateStyles = backgroundColor => {
  return {
    default: buildButtonState({ main: { $all: { backgroundColor }} }),
    active: buildButtonState({ main: { $all: { backgroundColor, opacity: 0.4, } } }),
    hover: buildButtonState({ main: { $all: { backgroundColor, opacity: 0.8, } } }),
    disabled: buildButtonState({ main: { $all: { backgroundColor, opacity: 0.6, } } }),
  }
}
```
this way you only have to define the main button state styles once, and you're not repeating your self

2020-10-01 00:01 UTC, mpcarolin approved these changes
🚀

2020-10-01 00:30 UTC, daniel112 commented on src/theme/components/button/evfButton.js
> +    disabled: {
updated

2020-10-01 00:37 UTC, merged