Zen 275 set session selected
simpleviewinc/tap-events-force pull request #60
Opened 2020-09-28 17:08 UTC by daniel112

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-275)

## Context

* a session item can be 'booked' by hitting the 'select' button
* if single user, update reducer to isSelected
  * call sessionBookingRequest - to book right away
* if multi-user, call the open modal, to open the group modal selection

## Goal

* Create the action `setSessionSelected`
* Setup the `BookingButton` component in the gridItem so we can easily test this action
   * NOTE: the bookingButton is not complete. it will be fully handled on 
        * https://jira.simpleviewtools.com/browse/ZEN-371
        * https://jira.simpleviewtools.com/browse/ZEN-268

## Updates

* List the updates you made to the codebase. Use your best judgement on how detailed the description should be
* *Name of file modified*
  * What changed in this file? Why?

## Testing

* List out the steps you took to test your changes
* Use the template below for listing out your testing steps
  ```
    * <Function> Testing:
      * Step 1
      * Step 2
      * Step n
      * Verify <some_expectations>
  ```
* Example Search Testing:
  * login to zsales.zerista.com as admin
  * Click on the 'Speakers' tab
  * Search for 'billy bob'
  * Verify that the speaker user shows up

2020-09-30 22:15 UTC, mpcarolin reviewed
Looking good and passed testing. I have a couple of questions in the comments.

2020-09-30 22:15 UTC, mpcarolin commented on src/actions/session/setSessionSelected.js
> +export const setSessionSelected = session => {
I think this could be renamed to something else (`selectSession`?),  because `setSessionSelected` sounds like we are storing the selected session or its id in the items store, but really this is either opening a modal or making a booking request.

2020-09-30 22:15 UTC, mpcarolin commented on src/components/button/bookingButton.js
> +      onClick={() => setSessionSelected(session)}
should put this in a `useCallback`

2020-09-30 22:15 UTC, mpcarolin commented on src/actions/session/setSessionSelected.js
> +  const attendeesCp = items && Array.from(items.attendees)
what does the `Cp` mean?

2020-09-30 22:15 UTC, mpcarolin commented on src/actions/session/setSessionSelected.js
> +export const setSessionSelected = session => {
I am also storing the selected session for the group booking modal. I'll probably move that here.

2020-09-30 22:15 UTC, mpcarolin commented on src/actions/session/setSessionSelected.js
> +export const setSessionSelected = session => {
what is the difference between the selected session and `activeSession` in the store?

2020-09-30 22:35 UTC, daniel112 commented on src/actions/session/setSessionSelected.js
> +  const attendeesCp = items && Array.from(items.attendees)
copy

2020-09-30 22:38 UTC, lancetipton requested changes
Looks good. Only a few minor things. Some are just suggestions. You don't have to do it.

2020-09-30 22:38 UTC, lancetipton commented on src/actions/session/setSessionSelected.js
> +  if (!session) return
In `non-production` environments we should log a warning here. That way it doesn't just fail silently
* Might be good to add a log helper to first check the current NODE_ENV, and log a warning 

Could look something like this =>
```js
/**
 * Helper to log messages when not in production
 * @param {string} type - Type of log message. Must be one of log, info, dir, warn, error
 * @param {Array} toLog - Data to be logged
 */
export const devLog = (type, ...toLog) => (
  process.env.NODE_ENV !== 'production' &&
    console[type] &&
    console[type](...toLog)
)
```

Then you can call it like this => 
```js
devLog(`warn`, `Action "setSessionSelected" requires a valid session. Instead received`, session)
```

You could also add helpers like this => 
```js
devLog.log = (...toLog) => devLog(`log`, ...toLog)
devLog.trace = (...toLog) => devLog(`trace`, ...toLog)
devLog.debug = (...toLog) => devLog(`debug`, ...toLog)
devLog.info = (...toLog) => devLog(`info`, ...toLog)
devLog.dir = (...toLog) => devLog(`dir`, ...toLog)
devLog.warn = (...toLog) => devLog(`warn`, ...toLog)
devLog.error = (...toLog) => devLog(`error`, ...toLog)
```

Then you could call like this => 
```js
devLog.warn(`Action "setSessionSelected" requires a valid session. Instead received`, session)
```

If you do this, replace any other log warnings that already exist, like the one in `actions/modals/removeModal.js` on line 35

2020-09-30 22:38 UTC, lancetipton commented on src/theme/components/grid/gridItem.js
> +      height: 'fit-content',
This doesn't work on mobile. Try switching it to 
```js
    flexDirection: 'row',
    alignSelf: 'flex-start',
```
If it doesn't look good with that, then use the `$web` and `$native` to separate the styles

2020-09-30 22:38 UTC, lancetipton commented on src/theme/components/grid/gridRowContent.js
> +      paddingBottom: 10,
These could just be
```js
pB: 10,
pL: 10
```
Or you could use the padding helper from keg-components
```js
import { kegComponentsTheme as theme } from 'SVTheme/kegComponentsTheme'

  column2: {
    main: {
      flex: 1,
      flexDirection: 'column',
      ...theme.padding(10, ['bottom', 'left']),
    }

```

2020-09-30 23:32 UTC, daniel112 commented on src/actions/session/setSessionSelected.js
> +export const setSessionSelected = session => {
`activeSession` is not used atm.
i think the idea behind it was to determine which session item the user clicked on for mobile expand. but we're not going down that route anymore i dont think

2020-09-30 23:38 UTC, daniel112 commented on src/components/button/bookingButton.js
> +      onClick={() => setSessionSelected(session)}
updated

2020-09-30 23:42 UTC, daniel112 commented on src/actions/session/setSessionSelected.js
> +export const setSessionSelected = session => {
il update the name

2020-09-30 23:52 UTC, daniel112 commented on src/theme/components/grid/gridRowContent.js
> +      paddingBottom: 10,
updated to use shortCut

2020-09-30 23:58 UTC, daniel112 commented on src/theme/components/grid/gridItem.js
> +      height: 'fit-content',
updated to platform specific styles

2020-10-01 16:57 UTC, daniel112 commented on src/actions/session/setSessionSelected.js
> +  if (!session) return
added this helper in the utils
updated `selectSession`, `removeModal`, `formatPrice` and `widthOf`

2020-10-01 17:08 UTC, daniel112 commented
updated from feedback

2020-10-01 22:10 UTC, lancetipton approved these changes
Only one small thing, and it's not really part of this ticket, so no big deal

2020-10-01 22:10 UTC, lancetipton commented on src/components/button/bookingButton.js
> +  if (!session) return null
This could be joined with the condition on line 17.

2020-10-01 22:51 UTC, merged