Zen 285 apply filter
simpleviewinc/tap-events-force pull request #61
Opened 2020-09-30 18:23 UTC by daniel112

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-285)

## Context

* the filter modal has filter items that users can select 1 or more of
* the user can then press the `apply` button that applies and saves the filter item selected

## Goal

* The filter modal should be able to filter the sessions

## Updates

* List the updates you made to the codebase. Use your best judgement on how detailed the description should be
* *Name of file modified*
  * What changed in this file? Why?

## Testing

### With the default Test Data
> If the filtering is applied by the booking state filters “Available”, “Selected”, “Waiting List” or “On Waiting List”, then these sessions allowBooking = false sessions must not be displayed in the filtered results.
  - change to day 1
  - filter by 'Big Data' only
  - see that only 1 session appears on day 1
  - now add any of the booking state filters on top of 'Big Data'
  - see that no session appears on day 1
     - this is because `allowBooking` is false on that one session

2020-10-05 21:39 UTC, lancetipton requested changes
Overall looks really good. There's a few small things to look at, but nothing major. 
There's one item I just left a note on, as I think it could be an issue, but I could not get it to fail; so for now, don't worry about it

2020-10-05 21:39 UTC, lancetipton commented on src/actions/session/mapSessionInterface.js
> +          setAgendaSessions(value, props.agendaDays)
This is great. It cleans this file up a lot. I think there's more that can be done too. Here's what I came up with this this file =>
```js
import { dispatch } from 'SVStore'
import { ActionTypes, Values } from 'SVConstants'
import { mapObj, snakeCase } from '@keg-hub/jsutils'
import { addModal } from 'SVActions/modals'
import { Modal } from 'SVModels/modal'
import { setAgendaSessions } from 'SVActions/session/setAgendaSessions'

const { CATEGORIES, SUB_CATEGORIES } = Values

/**
 * defines which sessionAgendaProps need to be mapped to subcategories
 */
const subCatMap = {
  settings: SUB_CATEGORIES.AGENDA_SETTINGS,
}

/**
 * If alert prop is valid, add a new modal item for alert
 * @param {<import('SVModels/alert').Alert)>} alert
 */
const checkAlert = alert => {
  alert?.title &&
    alert?.message &&
    addModal(new Modal({ type: CATEGORIES.ALERT.toLowerCase(), data: alert }))
}

const getDispatchPayload = (key, value) => {
  return !subCatMap[key]
    // by default, we use set items, so that if the component is mounted/remounted, data won't be duplicated
    ? {
        type: ActionTypes.SET_ITEMS,
        payload: { category: key, items: value }
      }
    // subcategories are upsert-merged, rather than set, since they
    // might need to be joined with data that was loaded from localStorage,
    // e.g. agendaSettings.activeDayNumber
    : {
        type: ActionTypes.UPSERT_ITEM,
        payload: { category: key, item: value, key: subCatMap[key] }
      }
}

/**
 * push the sessionAgendaProps items to our local state
 * @param {import('SVModels/sessionAgendaProps').SessionAgendaProps} props
 */
export const mapSessionInterface = props => {
  // loop through each key and dispatch accordingly
  props &&
    mapObj(props, (key, value) => {
      // ensure key exists in the items store first
      if(key !== CATEGORIES[snakeCase(key).toUpperCase()]) return

      // while mapping sessions, also map for 'activeSessions'
      // activeSessions are sessions sorted by day number
      key === CATEGORIES.SESSIONS &&
        setAgendaSessions(value, props.agendaDays)
      
      // Check for the alert prop, and call the checkAlert when it exists
      // Otherwise just dispatch the payload based on the key and value
      key === CATEGORIES.ALERT
        ? checkAlert(props.alert)
        : dispatch(getDispatchPayload(key, value))
    })
}

```

2020-10-05 21:39 UTC, lancetipton commented on src/components/modals/filter.js
> +    const isLabelOn = useMemo(() => {
This is great, but I would pull out, and put it in hook outside the loop. Like this => 
```js

// Above the LabelButtons component
const useLabelOn = (selectedCount, selectedFilters, item, label) => {
  // Check selectedCount before doing the loop. If none are selected, we save a few cpu cycles
  return useMemo(() => {
    return (
      selectedCount &&
      selectedFilters.some(
        item => item.identifier === label.identifier
      )
    )
  }, [ selectedFilters, selectedCount, label, item ])

}

 // Replace line 122 with this
const isLabelOn = useLabelOn(selectedCount, filters.selectedFilters, item, label)

``` 

It makes the code a lot easier to read and reason about.

2020-10-05 21:39 UTC, lancetipton commented on src/components/sessions.js
> +    applySessionFilters()
This looks like it could be a race condition. **I did a number of tests, but could not make it fail, so I'm just marking this incase the issue comes up at a later time.**

 * If the code in `mapSessionInterface` does not finish before the code in `applySessionFilters` is run, then the `applySessionFilters` might not get the most up-to-date data that it needs to filter the items
 * Also internally both actions call `setAgendaSessions`. So if `applySessionFilters` calls `setAgendaSessions` before `mapSessionInterface`
  * Then the items from `mapSessionInterface` will be what's in the store, and not the items from `applySessionFilters`
  * This could happen if `mapSessionInterface` is ever updated to be an **asynchronous call**

2020-10-05 21:45 UTC, daniel112 commented on src/components/sessions.js
> +    applySessionFilters()
yeah that makes sense if either of those functions are async, but since neither are, i dont think the race condition could occur here.
I agree that if we ever update this to be async we would have to address this

2020-10-05 21:53 UTC, daniel112 commented on src/actions/session/filters/applySessionFilters.js
> +  const sessions = items?.sessions
well on a case where:
1. user opens filter modal > applies some filter to the session > hit apply
    - sessions are now filtered accordingly
2. user opens the filter modal > unselect all the filters (essentially clearing) > hit apply
    - sessions should reset, so I would still need to call 
            - `setAgendaSessions` but with the original non filtered sessions
            - dispatch for `ACTIVE_FILTERS` so it no longer has any values in the array

so i could update it to something like
```
let filteredSessions = sessions
  if (selectedFilters.length > 0) {
    // filter by states
    let filteredSessions = applyStateFilters(selectedFilters, sessions)

    // filter by labels
    filteredSessions = applyLabelFilters(selectedFilters, filteredSessions)
  }
   // update agenda sessions store
   setAgendaSessions(filteredSessions, agendaDays)

  // set the current selectedFilters to activeFilters
  dispatch({
    type: ActionTypes.SET_ITEM,
    payload: {
      category: CATEGORIES.FILTERS,
      key: SUB_CATEGORIES.ACTIVE_FILTERS,
      item: selectedFilters,
    },
  })

```

2020-10-05 21:56 UTC, daniel112 commented on src/actions/session/filters/applySessionFilters.js
> +const applyStateFilters = (selectedFilters, sessions) => {
updated to `sessionsFromStateFilters `

2020-10-05 21:56 UTC, daniel112 commented on src/actions/session/filters/applySessionFilters.js
> +const applyLabelFilters = (labels, sessions) => {
updated to `sessionsFromLabelFilters `

2020-10-05 22:05 UTC, daniel112 commented on src/actions/session/filters/applySessionFilters.js
> +/**
updated

2020-10-05 22:12 UTC, daniel112 commented on src/components/modals/filter.js
> +    const isLabelOn = useMemo(() => {
will do. updated

2020-10-05 22:23 UTC, daniel112 commented on src/actions/session/mapSessionInterface.js
> +          setAgendaSessions(value, props.agendaDays)
works for me. updated

2020-10-06 17:43 UTC, lancetipton requested changes
Code looks good. Saw 2 very small things, and one of them does not require an update if you don't want to.

2020-10-06 17:43 UTC, lancetipton commented on src/actions/session/filters/applySessionFilters.js
> +    filteredSessions = sessionsFromStateFilters(selectedFilters, sessions)
Nothing wrong with this, but I would do it like this instead
```js
  const filteredSessions = selectedFilters.length > 0
    ? sessionsFromLabelFilters(
        selectedFilters,
        sessionsFromStateFilters(selectedFilters, sessions)
      )
    : sessions
```
One reason is because `let`'s  take more memory, so I try to use constants as much as possible.
But the main reason is, I just don't like `if ( some condition ){ ...do the thing }` 
  * It always seems so verbose to me
  * But again nothing wrong with what you did

2020-10-06 17:43 UTC, lancetipton commented on src/actions/session/filters/applySessionFilters.js
> +  const sessions = items?.sessions
Yah, that makes sense. Good point

2020-10-06 17:43 UTC, lancetipton commented on src/actions/session/mapSessionInterface.js
> + *
Can you add a description here

2020-10-06 17:53 UTC, daniel112 commented on src/actions/session/filters/applySessionFilters.js
> +    filteredSessions = sessionsFromStateFilters(selectedFilters, sessions)
got it. updated

2020-10-06 17:57 UTC, daniel112 commented on src/actions/session/mapSessionInterface.js
> + *
yup. updated

2020-10-06 18:01 UTC, lancetipton approved these changes
Looks good, thanks

2020-10-06 18:35 UTC, merged