ZEN-278: Group Booking Modal
simpleviewinc/tap-events-force pull request #63
Opened 2020-09-30 20:14 UTC by mpcarolin

**Ticket**: [ZEN-278](https://jira.simpleviewtools.com/browse/ZEN-278)

`[semver-status]: minor`

## Context/Goal

* For ZEN-278, we need a modal for group bookings
* To accomplish this, we also need a number of other updates 
* This PR is paired with [this PR for the hub](https://github.com/simpleviewinc/keg-hub/pull/32)

## Updates

* *Summary*: implemented the group booking modal, including updates to the store, utilities, hooks, UI, and integration with the paired changes in the hub

### Actions
* `src/actions/session/mapSessionInterface.js`
  * updated to call some additional initialization functions related to group booking
* `src/actions/attendees/initRestrictedAttendees.js`
  * creates the restricted attendees lists for each session and sets that in the items store 
* `src/actions/attendees/initSortedAttendees.js`
  * creates a map of ticket ids to that tickets' eligible attendees, then sets it in the items store
* `src/actions/attendees/setAttendeesByTicket.js`
  * the action for uploading the tickets->attendees map
* `src/actions/attendees/setRestrictedAttendeeIds.js`
  * the action for uploading the sessions->restricted-attendees map
* `src/actions/session/booking/sessionBookingRequest.js`
  * updated to work with input of a session id and an attendee ids list
* `src/actions/session/booking/sessionWaitingListRequest.js`
  * created this action for firing the list request event
* `src/actions/session/booking/setBookingList.js`
  * action to set the current list of attendees to be booked to the active group booking modal session
* `src/actions/session/booking/setCurrentSessionId.js`
  * action to set the id of the session for the group booking modal
* `src/actions/session/booking/setSessionCapacity.js` 
  * sets the current capacity of the session in the active group booking modal. This can change when users select or deselect an attendee checkbox
* `src/actions/session/booking/setWaitingList.js`
 * Sets the list of ids of attendees who should be put on the waiting list for the session of the active group booking modal.

### Assets
* `src/assets/icons/evf/elements/checkmark.js`
  * added the svg icon for the events force checkmark
* `src/mocks/eventsforce/testStyles.css`
  * fixed some class names

### Components

#### Group Booking
* `src/components/booking/attendeeBookingList.js`
  * vertical list of attendees to be booked/waitlisted, displayed with checkboxes
* `src/components/booking/attendeeCheckboxItem.js`
  * wrapper around `EvfCheckbox` with attendee-specific styling/logic
  * includes different appearances for an attendee that is waiting
* `src/components/booking/groupBooker.js`
  * root component that is placed in the booking modal as its content
* `src/components/booking/groupBookingOptions.js`
  * the middle section of the group booking modal, with all of the sections of attendees
* `src/components/booking/groupBookingSection.js`
  * checkbox-group of attendees, with a header and styling

#### General
* `src/components/checkbox/evfCheckbox.js`
  * a wrapper around the keg-component's checkbox, but with evf-styling
* `src/components/dates/dayToggle.js`
  * this appears to be the work of the linter & prettier plugins

#### Modals
* `src/components/modals/groupBooking.js`
  * refactored a bit just to wrap the `GroupBooker` and focus only on modal-specific styling and logic
* `src/components/modals/renderModals.js`
  * removed the attendees prop passing

#### Sessions
* `src/components/sessions.js`
  * updated to use the `useStoreItems` hook, to simplify getting data from the store
  * added support for waiting list request event

#### Constants
* `src/constants/values.js`
  * added new categories and sub-categories needed for the group booker, a new event, and the ticket type enum

#### Containers
* `src/containers/rootContainer.js` and `src/containers/testContainer.js`
  * updated to use the .js file for data, rather than the json
  * added test waiting list callback that logs output

### Hooks
* `src/hooks/booking/useBookingLists.js`
  * hook to acquire the initial booking and waiting lists for a session
* `src/hooks/booking/useWaitingSet.js` and `src/hooks/booking/useBookingSet.js`
  * returns the current booking and waiting lists as sets
* `src/hooks/booking/useCurrentSession.js`
  * returns the active session being used for the group booking modal
* `src/hooks/booking/useGroupCounts.js`
  * computes some memoized counts of the attendee data structures
* `src/hooks/booking/useInitGroupBooking.js`
  * initializes the store items related to the group booking modal
* `src/hooks/booking/useRestrictedAttendeeIds.js`
  * gets the current list of attendees who cannot book a given session
* `src/hooks/booking/useSessionBooking.js`
  * gets callbacks for booking attendees
* `src/hooks/models/useAgenda.js`
  * updated to use the `useStoreItems` hook
* `src/hooks/models/useTicketsForBooking.js`
  * gets the tickets needed for booking

### Models
* `src/models/*`
  * added models for BookedTicket and Ticket

### Reducers
* `src/reducers/initialStates/groupBooking.js`
  * set the initial state for the groupBooking category
* `src/theme/colors.js`
  * added some colors and updated `setColors` to default to the existing colors array if the css value is not defined

### Utils
* `src/utils/models/attendees/buildRestrictedAttendeeSet.js`
  * creates the set of restricted attendees for a given session
* `src/utils/models/attendees/countAttendeesByTicket.js`
  * counts all the attendees in the attendeesByTicket map
* `src/utils/models/attendees/getTicketForAttendee.js`
  * gets the ticket the attendee is ready to book
* `src/utils/models/attendees/isAttendeeRestricted.js`
  * indicates if an attendee cannot book a session
* `src/utils/models/tickets/getAllBookedTickets.js`
  * gets all the booked tickets in a flattened array
* `src/utils/models/tickets/sortTickets.js`
  * sorts tickets by display order

## Testing

* `keg d package run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-278-groupbooking-modal-body`
* navigate to the `/test` page

### Modal with limited capacity and existing attendee state
* select the button titled "Group booking Demo 2 - limited spots"
* there are a number of things to verify:
  * certain attendees should be pre-selected to match their current state with the session
    * Penelope O'Connor should already be on the waiting list
    * Unnamed, Dr Lucy Jones, and another Unnamed should be selected with blue checkboxes (=== on the booking list)
  * `Unnamed` attendees have italicized font
  * any attendee already on the waiting list for a session like this one (that has more capacity than attendees to book), should: 
    * show an `On waiting list` box to its right
    * display a dark gray background checkbox
    * when in mobile-view, it should display the text `(waiting)` next to the attendee name
    * unselecting the attendee, then selecting it again, should put it on the booking list (blue checkbox) provided that the capacity can support it
  * any attendee on the booking list for a session like this one (again, more capacity than need) should:
    * show a primary-colored checkbox background
  * selecting an unselected attendee checkbox should decrement the capacity at the top right of the modal
  * unselecting a selected attendee should increment it
  * if you select an unselected attendee when the capacity is 0, it should be put on the waiting list and the capacity should remain at zero
  * certain attendees should be unselectable due to being restricted from booking certain sessions in the modal. In the test data, they should be attendees `Vic Vinegar` and `Hugh Honey`. 
  * you should be able to click on an attendee on both its name text and its checkbox
  * hitting `book selected` should currently log out two things: 
    * "Emitted event sessionBookingRequest <session id> <array of ids of attendees with blue checkboxes>"
    * "Emitted event sessionWaitingListRequest <session id> <array of  [...]

2020-10-01 20:59 UTC, daniel112 requested changes
looks good overall. left a few comments regarding cleanup and design
also don't forget to rebase. so it can be tested in Safari

2020-10-01 20:59 UTC, daniel112 commented on src/components/booking/attendeeCheckboxItem.js
> + * @param {*} param0
can you add the props here

2020-10-01 20:59 UTC, daniel112 commented on src/components/booking/attendeeBookingList.js
> + * @param {Object} session
you can swap this out with `@param {import('SVModels/session').Session} session` 
so we can get the intellisense/autocomplete for people who uses them

2020-10-01 20:59 UTC, daniel112 commented on src/components/booking/attendeeBookingList.js
> + * @param {Array<Attendee>} props.attendees - attendee list for current section
this one too `@param {Array<import('SVModels/attendee').Attendee>} props.attendees`
you only have to do the import in the jsdoc if you didn't actually import it in the file

2020-10-01 20:59 UTC, daniel112 commented on src/components/booking/groupBookingSection.js
> +      title={name}
somehow the title needs to have the className `ef-modal-body-header`

also the styling on the header text is wrong according to the mockup. it should match the styles/coloring as the top right header item. + they have the same className

![image](https://user-images.githubusercontent.com/3317835/94858565-1421fd80-03e8-11eb-91b6-e98375b40495.png)

2020-10-01 20:59 UTC, daniel112 commented on src/components/checkbox/evfCheckbox.js
> + * @param {*} props.styles.content.right - style of rightward text
these should be `object` type right? not any?

2020-10-01 20:59 UTC, daniel112 commented on src/components/checkbox/evfCheckbox.js
> +    <Checkbox
need to somehow pass in `ef-modal-sub-header` className to the name text
![image](https://user-images.githubusercontent.com/3317835/94859112-e4272a00-03e8-11eb-95a7-313c580f2e9b.png)

2020-10-01 20:59 UTC, daniel112 commented on src/components/modals/groupBooking.js
> +  if (!session) return
this should return null right? since its a component

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useBookingLists.js
> + */
can we add the types to these props?

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useInitGroupBooking.js
> + * @returns {boolean} true if the store is initialized with the data, false otherwise
can you add the types here

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useInitGroupBooking.js
> +  )
should this be moved to the init hook then?

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useRestrictedAttendeeIds.js
> +export const useRestrictedAttendeeIds = sessionId => {
can we add jsdoc here?

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useBookingLists.js
> +export const useBookingLists = (
this hook seems to do a lot of things and is not dependent on any other helpers, i think it would be useful to add a unit test for this one

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useCurrentSession.js
> +export const useCurrentSession = () => {
the name `useCurrentSession` makes me think that this could be used generally for different types of booking, but the logic seems to be tied to `group booking`. 

maybe we can rename it something else to signify that it's only used within group booking?

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useSessionBooking.js
> + * @param {*} session
can we add the type here

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/booking/useWaitingSet.js
> + * const waitingList = useBookingSet()
typo : `const waitingList = useWaitingSet()`

2020-10-01 20:59 UTC, daniel112 commented on src/hooks/models/useTicketsForBooking.js
> + * @param {*} attendeesByTicket
types por favor

2020-10-01 20:59 UTC, daniel112 commented on src/models/bookedTicket.js
> +   * Attendee class model
typo on the name

2020-10-01 20:59 UTC, daniel112 commented on src/models/ticket.js
> +   * Attendee class model
typo on the name

2020-10-01 20:59 UTC, daniel112 commented on src/theme/components/booking/attendeeCheckboxItem.js
> +      alignItems: 'center',
for styles that applies to all sizes. can we just put them in `$xsmall` ? if we already have the sizes key defined on the style obj.
i see you did that on some of them already (`groupBookingOptions` styles)

2020-10-01 20:59 UTC, daniel112 commented on src/theme/components/group/checkboxGroup.js
> +const primaryItem = {
just marking this file for reference. idk if its related to the stuff on this file.

there seems to be some inconsistencies with the text styles not changing sizes when resized from `small` to `xsmall`
- i see that some of the checkbox item changed sizes (`Mrs Penelope O'Connor`), but some kept the same fontSize as `$small`. except until I click the checkboxes
![modal-size](https://user-images.githubusercontent.com/3317835/94862201-834e2080-03ed-11eb-9e1b-acf3fd3e40a4.gif)

2020-10-01 20:59 UTC, daniel112 commented on src/utils/models/attendees/getTicketForAttendee.js
> + * @param {*} tickets
needs the types in jsdoc

2020-10-01 20:59 UTC, daniel112 commented on src/utils/models/attendees/isAttendeeRestricted.js
> + * @param {*} session
types?

2020-10-01 20:59 UTC, daniel112 commented on src/utils/models/tickets/sortTickets.js
> + * @param {*} tickets
type?

2020-10-01 21:50 UTC, lancetipton requested changes
Looking really good. There's a few things to look at. Let me know if you have questions.

2020-10-01 21:50 UTC, lancetipton commented on src/components/dates/dayToggle.js
> +  const dateFormat = isMobileSize
Seems like this whole function could be converted into a hook. Something liek this => 
```js
/**
 * Formats the date into a string of the form D MMMM YYYY
 * @param {string} currentDate - current date string
 * @param {boolean} isMobileSize
 */
const useDateString = (currentDate, isMobileSize, widthCheck) => {
  return useMemo(() => {
    const parsedDate = parse(currentDate, `yyyy-MM-dd`, new Date())
    const dateFormat = isMobileSize
      ? 'd MMM'
      : widthCheck
        ? 'd MMM yyyy'
        : 'd MMMM yyyy'

    return currentDate ? format(parsedDate, dateFormat) : 'N/A'

  }, [ currentDate, isMobileSize, widthCheck ])

}

//Then call it like this on line 49
  const dateStr = useDateString(
    date,
    isMobileSize(theme),
    dims.width < 750
  )

  const dayText = `Day ${dayNumber} - ${dateStr}`
```

2020-10-01 21:50 UTC, lancetipton commented on src/components/modals/groupBooking.js
> +      <GroupBooker
Not sure when this happened, but theres a spelling mistake in a prop of the base modal => `dissmissedCBRef` should be `dismissedCBRef`
If you can fix it that would be appreciated, or if you think it should go into a different ticket that's fine too

2020-10-01 21:50 UTC, lancetipton commented on src/containers/testContainer.js
> +import testData from '../mocks/eventsforce/testData.js'
Now that you have updated this, can we delete the `.json` version
It can be confusing which one is being used when you want to edit it directly

2020-10-01 21:50 UTC, lancetipton commented on src/hooks/booking/useBookingLists.js
> +    return attendees
This should be converted to `reduce`.
I'm yet to find a case where `filter/map` could not be converted into a `reduce`, which only requires one iteration.
I'm sure it exists though.

2020-10-01 21:50 UTC, lancetipton commented on src/hooks/booking/useInitGroupBooking.js
> +export const useInitGroupBooking = (
Ohh, this is very nice. Well done sir. Great abstraction of complicated logic to simplify it.

2020-10-01 21:50 UTC, lancetipton commented on src/hooks/booking/useSessionBooking.js
> +        bookingList.delete(id) &&
It almost seems like these `sets` are little micro stores. Like a form of internal state. 
Part of me feels like they are **hacks**, and another part of feels like they **awesome**
I get the use case, but it feels like it could have been solved in a different way
  * Like using the `useReducer` hook to manage their state. 
  * Which is essentially what they are
  * They feel like a reimplementation of that, which means we're just duplicating functionality.
  * Honestly I'm not sure how I feel about them at this point. But they work, so I guess we go with it for now

2020-10-01 21:50 UTC, lancetipton commented on src/mocks/eventsforce/testStyles.css
> +.ef-sessions-button-default {
Are you sure about this change? From the mock ups, there's some places where it's `ef-button-default` and other places where it's `ef-sessions-button-default`

2020-10-01 21:50 UTC, lancetipton commented on src/theme/colors.js
> +  // override the colors object with values from updated,
oooo, I like this. Well done

2020-10-01 21:50 UTC, lancetipton commented on src/utils/models/tickets/getAllBookedTickets.js
> +    ...bookedTickets,
This is added twice, see line 14

2020-10-02 00:45 UTC, mpcarolin commented on src/components/booking/attendeeCheckboxItem.js
> +        <Button
updated to remove hover styles so that user won't think it's interactive

2020-10-02 00:47 UTC, mpcarolin commented on src/theme/components/booking/attendeeCheckboxItem.js
> +          height: 31,
nice. updated

2020-10-02 00:47 UTC, mpcarolin commented on src/theme/components/modals/groupBookingModal.js
> +  fontWeight: '600',
updated

2020-10-02 00:48 UTC, mpcarolin commented on src/theme/components/booking/attendeeCheckboxItem.js
> +      alignItems: 'center',
updated

2020-10-02 00:50 UTC, mpcarolin commented on src/theme/components/modals/groupBookingModal.js
>              justifyContent: 'space-between',
updated

2020-10-02 00:50 UTC, mpcarolin commented on src/actions/tapIndex.js
>  export * from 'SVActions/modals'
👍

2020-10-02 21:01 UTC, mpcarolin commented on src/assets/icons/evf/elements/checkmark.js
> +export function Checkmark(props) {
updated

2020-10-02 21:02 UTC, mpcarolin commented on src/assets/icons/evf/svg/checkmark.svg
> +<svg width="10" height="7" viewBox="0 0 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">
the only motivation was to support eventually using a plugin to automatically generate the react components from the source svg, during the build step.

2020-10-02 21:05 UTC, mpcarolin commented on src/components/booking/attendeeCheckboxItem.js
> + * @param {*} param0
yep, updated

2020-10-02 21:08 UTC, mpcarolin commented on src/components/booking/attendeeBookingList.js
> + * @param {Object} session
updated

2020-10-02 21:10 UTC, mpcarolin commented on src/components/booking/attendeeBookingList.js
> + * @param {Array<Attendee>} props.attendees - attendee list for current section
updated

2020-10-02 22:33 UTC, mpcarolin commented on src/components/booking/groupBookingSection.js
> +      title={name}
updated

2020-10-02 22:34 UTC, mpcarolin commented on src/components/checkbox/evfCheckbox.js
> + * @param {*} props.styles.content.right - style of rightward text
updated

2020-10-02 22:34 UTC, mpcarolin commented on src/components/checkbox/evfCheckbox.js
> +    <Checkbox
updated

2020-10-02 22:34 UTC, mpcarolin commented on src/components/modals/groupBooking.js
> +  if (!session) return
updated

2020-10-02 22:38 UTC, mpcarolin commented on src/hooks/booking/useBookingLists.js
> + */
updated

2020-10-02 22:39 UTC, mpcarolin commented on src/hooks/booking/useInitGroupBooking.js
> + * @returns {boolean} true if the store is initialized with the data, false otherwise
updated

2020-10-02 22:40 UTC, mpcarolin commented on src/hooks/booking/useInitGroupBooking.js
> +  )
that was copypasta and forgot to remove it

2020-10-02 22:40 UTC, mpcarolin commented on src/hooks/booking/useInitGroupBooking.js
> +  )
updated

2020-10-02 22:43 UTC, mpcarolin commented on src/hooks/booking/useRestrictedAttendeeIds.js
> +export const useRestrictedAttendeeIds = sessionId => {
updated

2020-10-02 23:41 UTC, mpcarolin commented on src/hooks/booking/useBookingLists.js
> +export const useBookingLists = (
agreed, updated

2020-10-05 15:58 UTC, mpcarolin commented on src/utils/models/attendees/getTicketForAttendee.js
> + * @param {*} tickets
updated

2020-10-05 15:59 UTC, mpcarolin commented on src/utils/models/attendees/isAttendeeRestricted.js
> + * @param {*} session
updated

2020-10-05 16:01 UTC, mpcarolin commented on src/containers/rootContainer.js
> +  const [ text, setText ] = useState(JSON.stringify(testData))
updated

2020-10-05 16:01 UTC, mpcarolin commented on src/containers/testContainer.js
> +  const [ text, setText ] = useState(JSON.stringify(testData))
updated

2020-10-05 17:16 UTC, mpcarolin commented on src/theme/components/group/checkboxGroup.js
> +const primaryItem = {
Hmm, I could not recreate this (tried on chrome + ff, multiple sessions). It's possible I fixed this already. 

Please try again when I resubmit this. If you still encounter it can we hop on a call?

2020-10-05 17:17 UTC, mpcarolin commented on src/assets/icons/evf/svg/checkmark.svg
> +<svg width="10" height="7" viewBox="0 0 10 7" fill="none" xmlns="http://www.w3.org/2000/svg">
if we plan to never do that, they aren't necessary

2020-10-05 17:19 UTC, mpcarolin commented on src/hooks/booking/useCurrentSession.js
> +export const useCurrentSession = () => {
agreed, changed to `useBookingSession`

2020-10-05 17:45 UTC, mpcarolin commented on src/hooks/booking/useSessionBooking.js
> + * @param {*} session
updated

2020-10-05 17:45 UTC, mpcarolin commented on src/hooks/booking/useWaitingSet.js
> + * const waitingList = useBookingSet()
updated

2020-10-05 18:18 UTC, mpcarolin commented on src/utils/models/attendees/getTicketForAttendee.js
> + * @param {*} tickets
updated

2020-10-05 18:19 UTC, mpcarolin commented on src/hooks/models/useTicketsForBooking.js
> + * @param {*} attendeesByTicket
updated

2020-10-05 18:20 UTC, mpcarolin commented on src/models/bookedTicket.js
> +   * Attendee class model
updated

2020-10-05 18:20 UTC, mpcarolin commented on src/models/ticket.js
> +   * Attendee class model
updated

2020-10-05 19:25 UTC, mpcarolin commented on src/utils/models/attendees/isAttendeeRestricted.js
> + * @param {*} attendee
updated

2020-10-05 19:27 UTC, mpcarolin commented on src/actions/attendees/initRestrictedAttendees.js
> + * @param {Array<Session>} sessions
updated

2020-10-05 19:28 UTC, mpcarolin commented on src/actions/attendees/initSortedAttendees.js
> + * @param {Array<Attendee>} attendees
updated

2020-10-05 19:35 UTC, mpcarolin commented on src/actions/attendees/initRestrictedAttendees.js
> +export const initRestrictedAttendees = (sessions, attendees) => {
agreed, updated all the actions with validation

2020-10-05 19:35 UTC, mpcarolin commented on src/actions/attendees/initSortedAttendees.js
> +export const initSortedAttendees = (attendees, tickets, bookedTickets) => {
agreed, updated all the actions with validation

2020-10-05 19:36 UTC, mpcarolin commented on src/actions/attendees/setAttendeesByTicket.js
> +export const setAttendeesByTicket = attendeesByTicketMap => {
agreed, updated all the actions with validation

2020-10-05 19:54 UTC, mpcarolin commented on src/actions/attendees/setRestrictedAttendeeIds.js
> + * @param {string} sessionId
updated

2020-10-05 20:13 UTC, mpcarolin commented on src/actions/session/booking/sessionBookingRequest.js
> +export const sessionBookingRequest = (sessionId, attendeeIds = []) => {
yep updated

2020-10-05 20:13 UTC, mpcarolin commented on src/actions/session/booking/sessionBookingRequest.js
> +  else
updated

2020-10-05 20:25 UTC, mpcarolin commented on src/actions/session/booking/sessionWaitingListRequest.js
> +  if (!valid)
updated

2020-10-05 20:31 UTC, mpcarolin commented on src/actions/session/booking/setBookingList.js
> +  dispatch({
updated

2020-10-05 20:32 UTC, mpcarolin commented on src/actions/session/booking/setCurrentSessionId.js
> +  dispatch({
updated

2020-10-05 20:36 UTC, mpcarolin commented on src/actions/session/booking/setSessionCapacity.js
> +  dispatch({
updated

2020-10-05 20:36 UTC, mpcarolin commented on src/actions/session/booking/setWaitingList.js
> +/**
updated

2020-10-05 20:38 UTC, mpcarolin commented on src/assets/icons/evf/elements/checkmark.js
> +import * as React from 'react'
updated to use it

2020-10-05 22:31 UTC, mpcarolin commented on src/components/booking/attendeeBookingList.js
> +    const isBooking = bookingList.has(attendeeId)
updated

2020-10-05 22:33 UTC, mpcarolin commented on src/components/booking/attendeeCheckboxItem.js
> +        { isMobile && <Text style={waitingStyles?.waitText}>(waiting)</Text> }
agreed, but the linter won't let me lol (< 80 characters, the other one is > 80)

2020-10-05 22:38 UTC, mpcarolin commented on src/components/booking/attendeeCheckboxItem.js
> +          themePath='button.outline.default'
thanks, I intended to update that. Updated the `waitingStyles.button` colors to be the right grey.

2020-10-05 22:40 UTC, mpcarolin commented on src/components/booking/groupBooker.js
> +  const topSectionStyles = styles?.content?.topSection || {}
updated

2020-10-05 22:41 UTC, mpcarolin commented on src/components/booking/groupBooker.js
> +    session?.capacity.isUnlimited
updated

2020-10-05 23:01 UTC, mpcarolin commented on src/components/dates/dayToggle.js
> +  const dateFormat = isMobileSize
Nice, I like it.  Updated! (also fyi I didn't have any changes related to dayToggle in this PR, those diff-changes I think were just the linter, but happy to add the hook).

2020-10-05 23:05 UTC, mpcarolin commented on src/components/modals/groupBooking.js
> +      <GroupBooker
updated 👍

2020-10-05 23:08 UTC, mpcarolin commented on src/containers/testContainer.js
> +import testData from '../mocks/eventsforce/testData.js'
done

2020-10-05 23:13 UTC, mpcarolin commented on src/hooks/booking/useBookingLists.js
> +    return attendees
I think you're right -- pretty sure `reduce` can always be substituted. I sometimes prefer to do `filter` then `map` just because I think it's more readable, but it also does make an additional unnecessary pass. I went ahead and updated this to reduce 👍

2020-10-05 23:30 UTC, mpcarolin commented on src/mocks/eventsforce/testStyles.css
> +.ef-sessions-button-default {
Yeah I noticed that, I simply went with what most of the others were using. But I went ahead and asked Adrian for clarity here: https://simpleview-workspace.slack.com/archives/C0149C412E7/p1601940496023000

2020-10-05 23:30 UTC, mpcarolin commented on src/mocks/eventsforce/testStyles.css
> +.ef-sessions-button-default {
If he says it's the one without `sessions`, I'll update this

2020-10-05 23:33 UTC, mpcarolin commented on src/utils/models/tickets/getAllBookedTickets.js
> +    ...bookedTickets,
I actually need both

The booked ticket type is a bit odd. Each booked ticket can have a property `bookedSubTickets`, which are valid booked tickets themselves that might be the ones we need to use to find the right ticket for an attendee.

So `getAllBookedTickets` is creating a single flattened array of the booked tickets and all of the subBookedTickets.

2020-10-06 00:02 UTC, mpcarolin commented on src/hooks/booking/useSessionBooking.js
> +        bookingList.delete(id) &&
I've been thinking about this for awhile and here's how I feel right now.

### Pros:
- data and the mutating functions are encapsulated into a single object, so the consumer doesn't need to know or care about the details 
- it's reusable with any storage solution, like redux or anything else. For example, here's it used local to a single component:
```js
// local example
const names = useSet([])
return (
   <NameList names={names.data} />
   { 
     names.data.map(name => 
       <button key={name} onPress={() => names.add(name)}>
          {name}
       </button>
     ) 
  }
)
```
* I think that's really nice and a lot simpler than adding set-logic to the functions for adding/removing items


### Cons
* it's not explicit. The object looks and behaves exactly like a standard JS Set, so it's easy for the consumer to believe that's the case, and then be surprised when it queues a rerender when mutated
* non-standard

I don't follow how its recreating `useReducer`, which is a full-on reducer that manages state through actions. `useReducer` returns a state object and a dispatch function. This is just a set, and the state itself is being stored in the redux store, so the hook isn't managing any global state itself, it's just providing an interface to access and mutating it.

I DO think that a reducer, either `useReducer` or `redux`, could do everything it's doing, just differently. I think we could add a new action type to the items store, like `UNIQUE_ADD` that works this way. It still wouldn't be quite the same -- the consumer would have to import the actions and get the state through `useSelector` or `mapStateToProps`. It also wouldn't replace the benefit of using `useSet` local to a single component. 

For now I personally think the right answer is: add the `UNIQUE_ADD` action type support to the items reducer, and use that for getting set-behavior in our items store. But I would still keep the hooks, but only use them for local-component cases.

2020-10-07 21:03 UTC, mpcarolin commented on src/mocks/eventsforce/testStyles.css
> +.ef-sessions-button-default {
So Adrian got back to me, and apparently the one of us who is right is....neither of us lol: 

https://simpleview-workspace.slack.com/archives/C0149C412E7/p1602061359027400

2020-10-07 22:59 UTC, lancetipton commented on src/hooks/booking/useSessionBooking.js
> +        bookingList.delete(id) &&
What I meant by `recreating useReducer` is that it's accomplishing the same thing. It's a way to manage state locally. It just does it in a different way than `useReducer`, but at the end of the day, they both accomplish the same thing.

When you say `state itself is being stored in the redux store`, I don't think that's relevant. Where the initial state comes from doesn't matter. It could be a reducer store, originally hard coded values, or an internal API call, who cares.

The point is that it's used to manage state.  It does it well, and I actually think it' really cool, but we already have a number of ways to manage state, how they do it is just an implementation detail.

There's a number of upsides to using these other `systems`, in  that they are common and consistent within the react world. Which means less `keg-*` domain knowledge is required to interact with the system. If you're a react developer, you've at least heard of them. They also come with the added benefits of documentation and are through tested.

And there's a number of downsides to using the useSet hook, in that it's extra code to accomplish something we can already do. It requires domain knowledge of the hook to use it properly.

Now I'm not trying to say don't use it. I'm just not 100% sold on it being needed in this use case.

2020-10-09 16:06 UTC, mpcarolin commented on src/mocks/eventsforce/testStyles.css
> +.ef-sessions-button-default {
Updated with the new classes. Also updated the EvfButton component to use just classNames, rather than the `useParsedStyles`, which isn't necessary anymore after the theme updates.

2020-10-09 16:16 UTC, mpcarolin commented on src/hooks/booking/useSessionBooking.js
> +        bookingList.delete(id) &&
Spoke about this on calls. Going to move to `useReducer`, but with this ticket: https://jira.simpleviewtools.com/browse/ZEN-419

2020-10-09 22:04 UTC, lancetipton requested changes
Looks really good and all the things to what they should. There's a few items I brought up, but it's getting really close.

2020-10-09 22:04 UTC, lancetipton commented on src/components/button/evfButton.js
> +  const customStyles = useMemo(() => ({ type, styles }), [ type, styles ])
I'm not sure I understand why `useParsedStyle` was removed. That's the styles applied from the style sheet on the Dom. 
Yes the `useClassNames` should add the correct class. But due to `css` selector specificity, our dynamic style names could override the custom defined parsed styles. This ensures they do not.

2020-10-09 22:31 UTC, mpcarolin commented on src/theme/components/booking/groupBookingSection.js
> +          fontSize: 'inherit',
good point -- it isn't supported on mobile. Updated to be wrapped in `$web`

2020-10-09 22:35 UTC, mpcarolin commented on src/utils/models/attendees/getTicketForAttendee.js
> +  if (!bookedTicketForAttendee) return null
updated

2020-10-09 22:37 UTC, mpcarolin commented on src/utils/validation/validateEventResponse.js
> +  isValid ? console.log(...validMessages) : console.warn(...invalidMessages)
updated

2020-10-12 16:01 UTC, mpcarolin commented on src/utils/models/attendees/sortAttendeeIntoSections.js
> +    console.warn('Could not find a valid ticket for attendee. Skipping... \n', {
updated

2020-10-12 16:21 UTC, mpcarolin commented on src/components/button/evfButton.js
> +  const customStyles = useMemo(() => ({ type, styles }), [ type, styles ])
my mistake -- I thought it was just duplicating the styles. Updated it back.

2020-10-12 17:05 UTC, lancetipton commented on src/components/booking/attendeeCheckboxItem.js
> +        { isMobile && <Text style={waitingStyles?.waitText}>(waiting)</Text> }
Then update the linter. We should decide the best format for the code, not the linter

2020-10-12 17:20 UTC, lancetipton requested changes
Looks good. Just some very minor things. Thanks.

2020-10-12 17:20 UTC, lancetipton commented on src/components/button/evfButton.js
> +      parsed: theme.join(parsedActionStyles, customParsedStyles),
* Can you update this from `theme.join` to `theme.get`
* I'm planning to get rid of `theme.join` eventually, because it basically does the same thing as `theme.get`
  * Just it's more complicated, slower, and as of now uses `theme.get` under the hood.

2020-10-12 17:20 UTC, lancetipton commented on src/containers/rootContainer.js
> +  const [ text, setText ] = useState(formattedTestData)
I like that you separated the  `formattedTestData` out, looks a lot better. But we can take this a step further.
* We should just make a TestData Component. That way all this is not duplicated across multiple containers
* Not sure if you want to do it now, or just create a new Ticket for it? Either way works for me

2020-10-12 17:20 UTC, lancetipton commented on src/containers/testContainer.js
> +  const [ text, setText ] = useState(formattedTestData)
See comment above for `TestData` Component

2020-10-12 17:58 UTC, daniel112 commented on src/components/booking/attendeeCheckboxItem.js
> +        <Button
can you remove active style too

2020-10-12 18:10 UTC, daniel112 commented on src/components/booking/attendeeCheckboxItem.js
> + * @param {string?} props.className - optional class name for text
should be `textClassName` yea?

2020-10-12 18:10 UTC, daniel112 commented on src/components/booking/attendeeCheckboxItem.js
> + */
missing `onAttendeeSelected`

2020-10-12 18:15 UTC, daniel112 commented on src/components/checkbox/evfCheckbox.js
> + * @param {Object} props.styles.content.right - style of rightward text
missing `close` prop on the jsdoc

2020-10-12 18:18 UTC, daniel112 commented on src/hooks/booking/useBookingLists.js
> + * @param {Function?} isBookable - optional cb of form id => true/false if attendee is bookable.
this prop is no longer used in the function

2020-10-12 18:21 UTC, daniel112 commented on src/hooks/booking/useInitGroupBooking.js
> + * @param {boolean} initialCapacityExceedsNeed - if true, then the session has greater capacity than the number of bookable attendees
its missing `remainingCount` jsdoc

2020-10-12 18:24 UTC, daniel112 commented on src/hooks/booking/useCurrentSession.js
> +export const useCurrentSession = () => {
but we have single booking as well. so the name can still be misleading
`useGroupBookingSession` maybe?

2020-10-12 18:26 UTC, daniel112 commented on src/hooks/booking/useSessionBooking.js
> + * @param {number?} initialCapacity
this is not a param anymore

2020-10-12 18:44 UTC, daniel112 commented on src/theme/components/group/checkboxGroup.js
> +const primaryItem = {
looks good now

2020-10-13 15:52 UTC, mpcarolin commented on src/components/booking/attendeeCheckboxItem.js
> +        <Button
Updated to just make this its own simple component of a view wrapping a text. At this point, that's simpler than modifying the button any further.

2020-10-13 15:53 UTC, mpcarolin commented on src/hooks/booking/useCurrentSession.js
> +export const useCurrentSession = () => {
updated to `useGroupBookingSession`

2020-10-13 15:59 UTC, mpcarolin commented on src/components/button/evfButton.js
> +      parsed: theme.join(parsedActionStyles, customParsedStyles),
👍  updated

2020-10-13 16:48 UTC, mpcarolin commented on src/containers/rootContainer.js
> +  const [ text, setText ] = useState(formattedTestData)
Looks like you already did this with the `TestData` component 👍 

I integrated those changes onto this branch.

2020-10-13 16:50 UTC, mpcarolin commented on src/components/booking/attendeeCheckboxItem.js
> + * @param {string?} props.className - optional class name for text
yep, updated

2020-10-13 16:51 UTC, mpcarolin commented on src/components/booking/attendeeCheckboxItem.js
> + */
updated

2020-10-13 16:52 UTC, mpcarolin commented on src/components/checkbox/evfCheckbox.js
> + * @param {Object} props.styles.content.right - style of rightward text
updated

2020-10-13 17:06 UTC, mpcarolin commented on src/hooks/booking/useBookingLists.js
> + * @param {Function?} isBookable - optional cb of form id => true/false if attendee is bookable.
updated

2020-10-13 17:09 UTC, mpcarolin commented on src/hooks/booking/useInitGroupBooking.js
> + * @param {boolean} initialCapacityExceedsNeed - if true, then the session has greater capacity than the number of bookable attendees
Updated

2020-10-13 17:10 UTC, mpcarolin commented on src/hooks/booking/useSessionBooking.js
> + * @param {number?} initialCapacity
updated

2020-10-13 23:14 UTC, lancetipton commented on src/containers/rootContainer.js
> +  const [ text, setText ] = useState(formattedTestData)
No that's what I meant, I just needed those changes for what I was doing. All good

2020-10-14 00:03 UTC, lancetipton approved these changes
Looks good to me.

2020-10-14 00:20 UTC, daniel112 approved these changes
LGTM!

2020-10-14 00:47 UTC, merged