Zen 374 modal filter clear btn
simpleviewinc/tap-events-force pull request #67
Opened 2020-10-06 21:39 UTC by daniel112

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-374)

## Context

* Filter Modal should contain a `clear filter` button. as shown in the new specs powerpoint here https://docs.google.com/presentation/d/19PRD8-W6hhWZvl8u1IPUOAkdnUJunCQ2zgGntuxM9Wk/edit?ts=5f58932a#slide=id.g8b8266aa53_0_208

* it should:
    * only display if any filter has been selected
    * on press > clears out currently selected filter. does NOT apply it automatically

## Goal

* Add this `clear filters` button on the filter modal
* use the already existing action `clearSelectedFilters`

## Updates

* `src/components/modals/filter.js`
   * add the button and attach the action `clearSelectedFilters`
   * minor cleanup

## Testing

* Run `keg dpg run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-374-modal-filter-clear-btn`
* Open the filter modal > verify you dont see a `clear filters` button
* select some filters > verify you see the `clear filters` button now
* click on `clear filters` > verify that it clears out your selected filters

2020-10-08 19:00 UTC, lancetipton requested changes
Overall looks good. There's a few changes needed. Nothing major

2020-10-08 19:26 UTC, daniel112 commented on src/components/modals/filter.js
> +        hasSelectedFilters={filters?.selectedFilters?.length > 0}
yup just looking for the Boolean.
ill update it to use `Boolean()`

2020-10-08 19:38 UTC, daniel112 commented on src/components/modals/filter.js
> +const LabelButtons = ({ styles, labels, selectedFilters = [] }) => {
i can update it to use `noPropArr`
i see that there is several `noOp` helpers in `keg-components` and we also have one in `keg-core`.
should we just add it to `keg-core`? and use it from there instead of pulling from keg-components

2020-10-08 20:30 UTC, daniel112 commented on src/components/modals/filter.js
> +const LabelButtons = ({ styles, labels, selectedFilters = [] }) => {
michael has these changes on his PR.
I will sync my container with his pending changes

2020-10-08 20:30 UTC, daniel112 commented on src/components/modals/filter.js
> +const LabelButtons = ({ styles, labels, selectedFilters = [] }) => {
updated

2020-10-08 20:31 UTC, daniel112 commented on src/components/modals/filter.js
> +          styles={styles?.clearButton}
nice. never even noticed that.
i updated the clearbtn styles to have transparent bgcolor on active && hover

2020-10-08 20:31 UTC, daniel112 commented on src/theme/components/modals/filterModal.js
> +        clearButton: {
updated

2020-10-08 20:32 UTC, daniel112 commented
updated based on feedback and uploaded new package

2020-10-13 17:20 UTC, lancetipton approved these changes
Code looks good, and UI matches the mock up, but personally I think the mock up is wrong. 
* The clear button does not look correct
* The font size is too big, and it's too close to the Apply button
* It should have some type of hover interaction to match similar buttons like the filter button

What I suggest
Option 1:
* Move the clear filters button further way from the Apply button
* Make the `clear filters` text smaller
* Add the hover state back to the button, now that it's further way from the Apply button they won't be touching when in a hover state  

Option 2:
* Keep the clear filters button where it is
* Make the clear filters text smaller
* Remove the default underline of the clear filters text
* Add the underline back when in a hover state
* Animate the `clear filters` text to a darker gray on hover

Neither of these match the mock-up, so I'm going to approve it. But I think we should do one of the perviously mentioned option instead.

2020-10-13 19:05 UTC, daniel112 commented
updated the clear btn styles to have smaller font. more padding between the apply button. hover styles back

2020-10-15 16:41 UTC, merged