Zen 371 booking button states
simpleviewinc/tap-events-force pull request #75
Opened 2020-10-20 00:58 UTC by lancetipton

**Ticket**: [ZEN-371]([link_to_jira_ticket](https://jira.simpleviewtools.com/browse/ZEN-371))

**NOTES**
* A new key called `bookingStopped` has been added to the testData in some places.
* This is used to represent a session that has had it's booking stopped, but booking was allowed at some point
* Currently Events Force is not sending us any way to determine this state. I have reached out to them, but have not heard back
    * This will be updated once I get a response from them on what the key should be

## Context
* The grid container and grid items have buttons related to booking sessions
* The buttons should reflect the current state based on the session and attendees
* Specs doc: https://docs.google.com/document/d/1bZIMvNhg6fsU5Tf1edLcoBfpu8rR9qQLGf0Kx-DGMrw/edit#

## Goal
* Display the correct booking state for each session based on the session and attendees

## Updates
* `configs/eslintrc.config.js`
    * Add `c` for the `color` rule shortcut in re-theme
* `src/actions/session/selectSession.js`
    * Updated to accept a custom attendees array
    * This allows passing an empty array, which should remove attendees from the session
* `src/assets/icons/evf/elements/bookingCheck.js`
    * Added booking checkmark icon
* `src/assets/icons/evf/elements/digit.js`
    * This is not technically an icon, but it's used like one, and acts like one; so it made sense to go here 
* `src/assets/icons/evf/index.js`
    * Added the Icon name as a property of the wrapper component so it can be accessed outside the wrapper
* `src/components/button/bookingButton.js`
    * Updated to display the look of the booking button based on the booking state
* `src/components/button/evfButton.js`
    * Added disabled and children prop
    * Allows overwriting the text prop with child components
    * Allows setting the button to be disabled from outside the button
* `src/components/testData/testData.js`
    * Added a select component to switch the test data to different states
    * This makes it easier / quicker to test the state of the app based on different test data
    * Right now I've only added differnt booking states, but other states could be added
* `src/constants/values.js`
    * Updated the session booking state `available` to be `select`
    * This matches the text on the booking button like the other states
* `src/hooks/booking/useBookingState.js`
    * Custom hook to build the booking model for the session
* `src/hooks/booking/useBookingTimeConflicts.js`
    * Custom hook to get any time conflicts for attendees and the current session
* `src/mocks/eventsforce/bookingStates/*`
    * Added testData for different booking states
* `src/models/session/bookingState.js`
    * Model for a sessions booking state
* `src/theme/components/button/evfButton.js`
    * Added styles for the different booking states
* `src/utils/models/sessions/bookingStateFactory.js`
    * Builds booking state models based on teh passed in props
    * Creates helper methods for each booking state, that returns a booking state model
* `src/utils/models/sessions/getBookingState.js`
    * Added check for `bookingStopped`
    * This will most likely need to be updated once Events Force responds with what it should be

## Testing
**Notes**
* Pull the docker package  => [right click and select copy, the paste into your terminal](keg evf pack run docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-371-booking-button-states)
* Navigate to [http://local.kegdev.xyz/](http://local.kegdev.xyz/)
* Open the Test Data (JSON) editor
    * On the left you should see a select dropdown
    * This will allow you to switch to different booking states with pre-defined test data
    * [Looks like this](http://snpy.in/mnr2E3)
* Each option follows a naming convection to help test a particular state
    * The pattern goes like this => `[booking state]-[booking-mode]-[reason]`
        * `booking-state` - This is the state the button should be in when this option is selected
        * `booking-mode` - This is the booking mode based on the number of attendees
            * single (1 attendee)
            * grouped ( more then 1 attendee )
        * `reason` - This is just a simple reason for why it's in this state based on the test data
            * Really I just needed a `key` in the object to define the state and this is what I came up with
            * It really just gives a hint of what the test data represents
                * For example
                    * `conflict` => An attendee has a time conflict between 2 sessions
                    * `override` => There are attendees on the booking and waiting list, so the `on waiting list` state overrides the `selected` state
    * Remember to hit the apply button after switching the booking state from the select box

**Tests**

**Test 1**
* Go through each one of the different states from the select dropdown
* Validate the data in the test-data editor with what is being showing on screen for each session
    * Selecting different states should reflect a different state on the Booking Button
    * The look of the booking button should match the [mock-ups](https://www.figma.com/file/kTLTvkxNF7ziNe9dQee88n/sessions_v2?node-id=0%3A1)

**Test 2**
* Ensure
    * When selecting a group booking state, the group booking modal still opens
    * When selecting a disabled booking state, the booking button is disabled
    * When selecting the `(on waiting list | selected) and single mode`, and clicking the booking button
        * It should call the selectSession action, with an empty array
        * [This should print out in the inspector](http://snpy.in/54mmg5)

**Test 3**
* Make modifications to the test data, to try and get different states for the sessions
    * See if you can find a variation I might have missed

2020-10-21 19:55 UTC, mpcarolin requested changes
Overall looks good, but I noticed a few things.

* The checkmark is different from the spec, which looks like it uses a rounded checkmark icon with more padding in the circle:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/9517356/96775150-f4a14380-139b-11eb-9d0b-7751d5b01bb4.png">
* when in single-attendee mode, and the waiting list is available, and the the capacity is 0, and you try to book the attendee; then the app is calling the `sessionBookingRequest` action, but it actually needs to call the `sessionWaitingListRequest` action (same function signature though).   

#### Nice to have, but not blocking if you disagree
* when:
  * the button is in a disabled state; and
  * you are in a mobile view; and
  * you try to specifically press the select button in an expanded session
* then:  
    * it collapses the drawer. 
    * I think it would be better if it did nothing at all (stop event bubbling), rather than closing the drawer. The user might not want to close it yet. He or she might just want to see what happens when the button is selected (not yet realizing it's disabled). This also might lead them to think the button is what closed the drawer, even though it's not.

2020-10-22 01:15 UTC, daniel112 requested changes
looking hella slick. 
left a few comments to ponder about

2020-10-22 01:15 UTC, daniel112 commented on src/utils/models/sessions/bookingStateFactory.js
> +import { EVFIcons } from 'SVIcons'
referencing this file because its in the stack trace
`utils/models/agenda/__tests__/agendaDays.js`  unit test failed. our jest config for the tap isn't very robust

![image](https://user-images.githubusercontent.com/3317835/96806130-17e1e800-13c8-11eb-9518-500482936a1d.png)

2020-10-22 17:52 UTC, lancetipton commented on src/constants/values.js
> +    SELECT: 'select',
Updates

2020-10-22 17:53 UTC, lancetipton commented on src/actions/session/selectSession.js
> +    : sessionBookingRequest(
This has been fixed in the latest changes of this PR

2020-10-22 17:53 UTC, lancetipton commented on src/components/button/bookingButton.js
> +export const BookingButton = props => {
Updated

2020-10-22 17:53 UTC, lancetipton commented on src/components/testData/testData.js
> +      exists(update) && setText(update)
Nice catch, I'll take a look when I have a chance

2020-10-22 17:56 UTC, lancetipton commented on src/assets/icons/evf/elements/digit.js
> +export const Digit = props => {
I like it were it is, because visually it is the same as an icon. Gonna keep it were it is. We can chat further about this if you really want to

2020-10-22 17:56 UTC, lancetipton commented on src/utils/models/sessions/bookingStateFactory.js
> +import { EVFIcons } from 'SVIcons'
hmm... I'll take a look

2020-10-22 18:36 UTC, daniel112 commented on src/assets/icons/evf/elements/digit.js
> +export const Digit = props => {
nah thats fine. works for me

2020-10-22 19:09 UTC, daniel112 commented on src/components/button/bookingButton.js
> +      console.log(event)
can we remove this log? or put it as a devLog if its necessary

2020-10-22 19:21 UTC, daniel112 commented on src/actions/session/selectSession.js
> +    : sessionBookingRequest(
i see this working for a case where the booking btn state is `on waiting list`

but it still doesnt seem to work when the button state is on `waiting list`

steps:
1. change the Test Data (JSON) to `waitingList-single-capacity`
2. click on `waiting list` button
3. see log `Emitted event sessionBookingRequest 1`

2020-10-22 22:57 UTC, lancetipton commented on src/actions/session/selectSession.js
> +    : sessionBookingRequest(
Updated

2020-10-22 23:04 UTC, lancetipton commented on src/components/testData/testData.js
> +      exists(update) && setText(update)
Fixed

2020-10-22 23:06 UTC, lancetipton commented on src/components/button/bookingButton.js
> +      console.log(event)
Updated

2020-10-23 00:32 UTC, lancetipton commented on src/utils/models/sessions/bookingStateFactory.js
> +import { EVFIcons } from 'SVIcons'
I actually had a number of tests failing for odd reasons. I really hate how these tests are setup
Anyways, I fixed this test and all the others

2020-10-23 01:16 UTC, daniel112 approved these changes
the different states works as expected as far I can tell
unit tests also all passed again, woo

2020-10-23 17:34 UTC, merged