Zen 423 pending sessions
simpleviewinc/tap-events-force pull request #88
Opened 2020-11-10 21:07 UTC by mpcarolin

**Ticket**: [ZEN-423](https://jira.simpleviewtools.com/browse/ZEN-423)

## Context

* currently, our booking buttons (both group-booking and single) do not update based on the status of their booking requests
* they need to show a loading spinner, until the request completes

## Goal

* For group booking and single booking, show a loading spinner until the booking request completes (awaiting the callbacks to resolve)
* update the UI to look good around this
* also disable modal booking buttons until modifications are made

## Updates
* `apps/Sessions.js`
  * removed reference to EFDemoContainer since we do not need it any longer
* `src/actions/session/booking/sessionBookingRequest.js`
  * updated to call the waiting list and booking list in one function
* `src/actions/session/pending/clearPendingSession.js` && `.../setPendingSession`
  * created actions for setting and removing the pending session
* `src/components/booking/attendeeBookingList.js`
  * updated list to be disabled if the group booking session is pending 
* `src/components/booking/groupBooker.js`
  * added ui for button spinner, as well as logic for handling the pending state
  * dismisses modal when pending state transitions to not-pending
* `src/components/button/bookingButton.js`
  * updated with `isProcessing` styles when the associated session is pending
* `src/components/button/evfButton.js`
  * updated to allow processing styles to be defined by consumer
* `src/components/loading/evfLoading.js`
  * updated to allow consumer to set color
* `src/components/testData/testData.js`
  * updated with booking delay dropdown ui
* `src/containers/rootContainer.js`
  * updated to simulate a consumer booking-request update 
* `src/hooks/booking/useBookingLists.js`
  * refactored
  * updated hook to also return the *existing* lists (as reflected by the props)
  * updated to ensure it does NOT preselect attendees if at least one attendee is on the booking list (quick fix to a reported bug)
* `src/hooks/booking/useBookingState.js`
  * updated to include the `pending` state of a session with the booking button state
* `src/hooks/booking/useInitGroupBooking.js`
  * updated to start monitoring the booking and waiting lists for modification,
  * if modified, it will flag the session as "modified" so that the user can select 
  * ensured it only calls the callbacks when an associated list has been modified
the booking button (disabled when no modifications are yet made)
* `src/hooks/booking/useSessionBooking.js`
  * renamed some variables to be more clear
* `src/models/session/pendingSession.js`
  * added pending session model
* `src/reducers/initialStates/**.js`
  * added new initial states for new state I'm tracking:
    * pending session
    * modified session
* `src/utils/models/sessions/bookingStateFactory.js`
  * updated the `getDisabled` function to set buttons as disabled if there is a single pending session. They become enabled again once that pending session is no longer pending.
* `src/utils/pending/emitPendingEvent.js`
  * helper to emit the pending update event
* `renderModals.js`
  * updated to just render the last modal on the stack
  * the way it was done before -- rendering all but toggling the visible flag -- caused judder in the UI when an alert modal appears at the same time that the group booking modal is removed from the stack

## Testing

* `keg evf pack run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-423-pending-sessions`

* New testing features to know about
  * when you submit a booking or wait-list request, that request will now actually
    update the state of the app (only when testing, though, not in the built export)
    so that the attendees are put onto or removed from the right booking and wait lists
  * there are url parameters you can pass in to help with testing:
    * `bookDelay`: time in seconds to make a booking request wait (e.g. *.kegdev.xyz/?bookDelay=1), or select the `Booking Delay` dropdown in the testing drawer, to change the amount of time (in seconds) that the app waits before rerendering with the updated attendee state
      * -1 url parameter instructs the app to wait indefinitely
  * `state`: (e.g. *.kegdev.xyz/?state=select.single.limited) to load a state
  * `reject`: if set, booking requests will fail and show an alert modal whose body message is this parameter's value

### Modification and Disabled States
* in the default state that enables group booking, select a limited session
  * e.g. `Session on day 2 - limited capacity`, the first session shown on day 2
* in the group booking modal that appears, first verify that the `Book Selected` button is **disabled**.
  * this is disabled because the user has not yet made a modification to the booking and waiting lists
  * you should also see a red asterisk next to the `Select sessions for your group:` instructions at the top of the modal, suggesting to the user that a change is required
* now, select any attendee who is not already checked
  * verify that the book-selected button becomes enabled, and that the red asterisk disappears
* try any combination of attendee list changes, and verify that the disabled and asterisk UI always looks and behaves like you would expect
* finally, open a session that is unlimited and has preselected attendees
  * e.g. `session at same time other session with presenters and labels`, the second session on day 1
  * verify that the booking button is not disabled, since these attendees are pre-selected
  * verify that if you uncheck ALL attendees (returning the session to its initial state), the button becomes disabled

### Pending states
* load `http://evf-zen-423-pending-sessions.local.kegdev.xyz/?bookDelay=-1`
  * this will make the booking requests never complete
* try booking a session
  * verify that the booking button enters a pending state
  * it will show a loading spinner and the text "Processing"
  * verify that OTHER session booking buttons are put into a disabled state at this time
  * verify that dismissing the modal does not cancel the pending/loading state of the button
* try booking a session again, but this time, while its stuck loading, open the test data json editor.
  * edit the "alert" object at the top, making sure you set both its title and message
  * apply the changes
  * verify that an error modal appears
  * verify that the booking button **continues to show a loading spinner**
    * error handling for the booking request is handled through the promises
* now `http://evf-zen-423-pending-sessions.local.kegdev.xyz/?bookDelay=1`
  * this will make the booking request take 1 second before completing
* submit a booking request in a group booking modal. Then verify:
  * the group modal's booking button shows the "processing" text and loading-styles, for a second
  * it dismisses the modal when completed, and it no longer shows the "processing" text and styles on the booking button
  * other booking buttons are enabled again
  * the state updates to reflect your change
    * for example, when the modal dismisses itself, you should now see that booking button show the number of attendees you selected (or put on the wait list)
  * try this with any combination of changes:
    * adding to and removing from the booking list
    * adding to and removing from the waiting list
* do the same testing for single-booking states (ignoring modal-specific steps)

### Request Error Handling
* load `http://evf-zen-423-pending-sessions.local.kegdev.xyz/?state=default&bookDelay=1&reject=BooHoo`
* submit a booking request through a group booking modal
* verify that:
  * 1 second later, an alert modal appears
  * the alert modal's title is "Error"
  * the modal's message is "boohoo" (from the url parameter)
  * when you close the alert modal, the group booking modal does not resurface
  * the booking button is not in a pending/loading state anymore
  * verify that your booking did not go through
* load a single booking state: `http://evf-zen-423-pe [...]

2020-11-12 00:35 UTC, daniel112 requested changes
looks good. i feel like i looked at some of these before..
anyways, just some minor thing here and there

2020-11-12 00:35 UTC, daniel112 commented on src/components/sessions.js
> +const useAttendeeRequestEvent = (bookRequestCb, waitRequestCb) => {
jsdoc needs to be updated here

2020-11-12 00:35 UTC, daniel112 commented on src/hooks/booking/useInitGroupBooking.js
> +const useBookingModifyMonitor = (
its missing the `sessionId` jsdoc param

2020-11-12 00:35 UTC, daniel112 commented on src/theme/components/button/evfButton.js
> +    ...defaultTextStyle,
not sure if this is necessary if we are putting them inside the specific sizes already?

2020-11-12 17:55 UTC, mpcarolin commented on src/actions/session/mapSessionInterface.js
> +  if (alert?.title && alert?.message) {
correct but it `addAlertModal` will log a warning in that case, so I still think it makes sense to avoid calling it, otherwise there would be lots of warnings on every render without an alert

2020-11-12 18:18 UTC, mpcarolin commented on src/components/booking/groupBooker.js
> + * @param {Function} onSubmit - button submit callback
updated

2020-11-12 18:18 UTC, mpcarolin commented on src/components/modals/groupBooking.js
>   * @param {Array.<import('SVModels/attendee').Attendee>} props.attendees
updated

2020-11-12 18:18 UTC, mpcarolin commented on src/components/sessions.js
> +const useAttendeeRequestEvent = (bookRequestCb, waitRequestCb) => {
updated

2020-11-12 18:18 UTC, mpcarolin commented on src/hooks/booking/useInitGroupBooking.js
> +const useBookingModifyMonitor = (
updated

2020-11-12 18:18 UTC, mpcarolin commented on src/theme/components/button/evfButton.js
> +    ...defaultTextStyle,
updated

2020-11-12 18:52 UTC, daniel112 approved these changes
👍

2020-11-13 00:17 UTC, lancetipton requested changes
Overall looks good. Still a few things to work out
* We should try to keep group modals internal state should contained to that component
* This would help simply the logic and remove complexity
* We discussed this a bit in a meeting, but please feel free to ping me if you have questions

2020-12-01 20:45 UTC, mpcarolin commented on src/components/modals/baseModal.js
> +      removeModal(index)
But we are still managing the stack of modals, no? I needed this index to ensure that it removes the right modal, otherwise there was an edge case in which the group booker would incorrectly remove the error modal on its dismissal if an error was raised right after the request completed.

2020-12-01 20:46 UTC, mpcarolin commented on src/utils/pending/emitPendingEvent.js
> +import { Values } from 'SVConstants'
removed

2020-12-01 20:57 UTC, mpcarolin commented on src/actions/session/booking/sessionBookingRequest.js
> +const isValidAttendeeList = list => !list || isArr(list)
updated

2020-12-01 20:59 UTC, mpcarolin commented on src/actions/session/booking/setUserModifiedBooking.js
> +export const setUserModifiedBooking = (
this is resolved based on the changes introduced with the group booking context PR

2020-12-01 21:00 UTC, mpcarolin commented on src/actions/session/pending/setPendingSession.js
> +  emitPendingEvent(pendingSession)
no longer necessary, since we are now capturing the active modal's dismiss callback and calling that directly.

2020-12-01 21:51 UTC, mpcarolin commented on src/actions/session/booking/handleAttendeeRequest.js
> +const parseException = exception => {
https://github.com/simpleviewinc/keg-hub/pull/78

2020-12-03 18:55 UTC, daniel112 approved these changes
looks good. testing passes.
not a blocker, but if you could also post a container for the `keg-test-consumer` that would be helpful for spot checking

2020-12-03 23:13 UTC, lancetipton requested changes
Looking really good. Much cleaner than before. I left a few comments, but most of them are non-blocking, but there are a couple that should be looked at.

2020-12-04 21:27 UTC, mpcarolin commented on src/actions/session/booking/handleBookingRequests.js
> +    return Promise.reject('Bad input')
Agreed. I updated it to show an alert modal telling the user there was an internal issue and to try again later. 

If this error arose, it would be a bug either in our code or in the data the consumer passes in.

2020-12-04 21:30 UTC, mpcarolin commented on src/actions/session/mapSessionInterface.js
> +  if (alert === existingAlert) return
updated

2020-12-04 21:31 UTC, mpcarolin commented on src/actions/session/pending/clearPendingSession.js
> +  const pendingSession = { identifier: null }
updated

2020-12-04 21:31 UTC, mpcarolin commented on src/actions/session/pending/setPendingSession.js
> +  const pendingSession = { identifier: sessionId }
updated

2020-12-04 21:32 UTC, mpcarolin commented on src/components/modals/renderModals.js
> +export const RenderModals = modals => {
agreed, updated to `ModalManager`

2020-12-04 21:33 UTC, mpcarolin commented on src/components/modals/groupBooking.js
> +const useDismiss = () => {
agreed, I did that, but then I made everything much simpler overall since we only need to track one modal. Now you can dismiss a modal just by calling the action `hideActiveModal`, so that's what all the modals are doing.

2020-12-04 21:33 UTC, mpcarolin commented on src/components/sessions.js
> +      { RenderModals(modals) }
updated 👍

2020-12-04 21:34 UTC, mpcarolin commented on src/contexts/modals/modalProvider.js
> +    [ closeModalRef, component ]
ref isn't needed anymore since we just have one active modal, so I just removed that dependency entirely

2020-12-04 21:35 UTC, mpcarolin commented on src/mocks/eventsforce/evfModalBuilder.js
> +        {...props}
updated to just remove that. I think I needed it before, but don't anymore

2020-12-04 21:36 UTC, mpcarolin commented on src/actions/session/booking/handleBookingRequests.js
> +const parseException = exception => {
yep, updated to use that and removed this function

2020-12-04 23:18 UTC, lancetipton requested changes
Dude, this is so much cleaner. I love it.
* Great work, especially good job on the Modals update. 
* Noticed a bug
  * When you book some one to a session. then later want to un-book them from the session, there's no way to do that.

2020-12-07 20:12 UTC, mpcarolin commented on src/contexts/modals/modalProvider.js
> +    () => ({
Updated to just pass the component

2020-12-07 23:28 UTC, daniel112 approved these changes
all test cases passed.  left a few comments, which i feel like i asked before but I forgot what you said.
 its not blocking

2020-12-07 23:28 UTC, daniel112 commented on src/actions/modals/removeModal.js
> +export const removeModal = () => {
after the modal states update, it don't see this method being used anywhere. even after you close out the modal, the data is still stored locally.
- [image](https://user-images.githubusercontent.com/3317835/101417391-dee2d180-38a8-11eb-84fa-583a4d8212c6.png)

we're purposely not removing the modal because of some kind of animation delay when opening/closing modals right?
- would there be a time where its beneficial for us to clear out the activeModal state? if not
- should we just remove this action then since it's not being used

2020-12-07 23:29 UTC, mpcarolin commented on src/reducers/initialStates/modals.js
> +  [CATEGORIES.MODALS]: {
yeah good point, I'll close that once this gets merged

2020-12-07 23:34 UTC, mpcarolin commented on src/actions/modals/removeModal.js
> +export const removeModal = () => {
Yeah, I solely kept it around in case it's ever needed.

I think it does have value for cases when you specifically want or need the modal to be unmounted. When you just "hide" them with `hideActiveModal`, they are still mounted, only not visible. I think this way the choice is there.

I'm open to removing it, as we could always add it back in. I lean toward keeping this one though.

2020-12-07 23:45 UTC, daniel112 commented on src/actions/modals/removeModal.js
> +export const removeModal = () => {
Only reason I'm bringing it up is that we already have all the modals setup for this iteration and it doesn't seem like we need to use it for any of the modals that currently exists.

maybe in future iteration they would want us to make more modals where the specific case is relevant.

I really don't have a preference over it, so it's up to you. 
@lancetipton thoughts?

2020-12-08 17:34 UTC, lancetipton commented on src/actions/modals/removeModal.js
> +export const removeModal = () => {
If we're not using it now, what would change in the future to make us need it later? 
It seems that if it were needed, then we would have already used it.

That being said, I don't think there's an issue with keeping but
  * It should be removed from `actions/modals/index.js`. That way it's not included in the bundle
  * Add a note to the top of the file, so anyone else looking at it, knows it's not included

Or the other option, if just remove it. Which I'm good with as well.

2020-12-08 17:42 UTC, lancetipton approved these changes
Changes look good. The bug I found is resolved. I added a comment to the `removeModal` action issue, that @daniel112 brought up, but it's not blocking. 

Great work on this

2020-12-08 17:50 UTC, mpcarolin commented on src/actions/modals/removeModal.js
> +export const removeModal = () => {
Okay I'll go ahead and remove `removeModal`. It doesn't seem necessary yet, and I’d prefer it deleted over it being the only action not exported and having to leave a note about it.

2020-12-08 17:52 UTC, merged