Zen 427 group time conflicts
simpleviewinc/tap-events-force pull request #90
Opened 2020-11-12 21:20 UTC by mpcarolin

**Ticket**: [ZEN-427](https://jira.simpleviewtools.com/browse/ZEN-427)

## Context

* currently, the group booking modal does not disable attendee checkbox items if those attendees have a time block with the selected session

## Goal

* update the group booking modal to ensure that attendees with time-conflicts are disabled and greyed-out

## Updates

* `src/components/booking/attendeeBookingList.js`
  * updated to disable attendees checkbox items if they have a time conflict
* `src/hooks/booking/useBookingLists.js`
  * updated to ensure that attendees with time-conflicts are never pre-selected by the group booking modal
* `src/hooks/models/attendees/useIsAttendeeDisabledCallback.js`
  * created a more general hook, `useIsAttendeeDisabledCallback`, that checks if the attendee has either a time conflict OR is restricted from booking a session.
* `src/mocks/eventsforce/bookingStates/conflict.js`
  * just created a mock state for testing

## Testing

* `keg evf pack run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-427-group-time-conflicts`
* navigate to `http://evf-zen-427-group-time-conflicts.local.kegdev.xyz/?state=conflict.group.limited`
* select the second session
  * verify that `Mr. Frank Smith` is disabled. This is because Frank Smith is already booked against the first session, which you can see in the test data json. These two sessions have the exact same time block and day.
* now select the first session
  * verify both of the attendees are pre-selected (this is b/c the capacity of the session exceeds the number of attendees)
* select the `Book Selected` button
* now select the second session again
  * verify that both of the attendees are greyed out
* if you'd like, try any combination

2020-11-13 16:16 UTC, daniel112 requested changes
unit test had 1 failing test for me
I also have an edge case that i think we should cover for consistency

2020-11-13 16:16 UTC, daniel112 commented on src/hooks/booking/useBookingLists.js
>  import { useMemo } from 'react'
marking this file for the unit test that failed
![image](https://user-images.githubusercontent.com/3317835/99093510-cc1dfb00-258f-11eb-854b-a0debfc29f6c.png)

2020-11-13 16:16 UTC, daniel112 commented on src/hooks/models/attendees/useIsAttendeeDisabledCallback.js
> +export const useIsAttendeeDisabledCallback = (session, attendees) => {
for an edge case where every single person in the group is booked against a session. it should disable the booking button on the rest of the sessions that's conflicting similar to how it is for the single booking.

current behavior still enables the booking button, but when you open it, all users are disabled
![image](https://user-images.githubusercontent.com/3317835/99094311-e0162c80-2590-11eb-99c9-28a89c4b6a7d.png)

2020-11-13 19:14 UTC, mpcarolin commented on src/hooks/booking/useBookingLists.js
>  import { useMemo } from 'react'
fixed

2020-11-13 19:16 UTC, mpcarolin commented on src/hooks/models/attendees/useIsAttendeeDisabledCallback.js
> +export const useIsAttendeeDisabledCallback = (session, attendees) => {
Good catch. This had to do with the hook `useGroupCounts`, which was only counting using the restricted attendees. I updated it to factor in the time-conflicted ones as well 👍

2020-11-15 07:30 UTC, lancetipton approved these changes
Code looks good. Most items worked as expected, but I did run into something that may be an issue
When clicking on the first session from the test steps 4th bullet point, only one attendee is selected => http://snpy.in/LRYnCT
  * Which I'm pretty sure is the correct behavior
  * But the test says both users should be selected
    * From my understanding, it should only set all users as selected, when no attendees have been booked to the session
    * But because one of the attendees is booked to the session, it does not auto select all of them
  * When I remove the attendee from being booked to that session. Then when I open the modal, all users are auto selected.

So I'm going to approve because I believe everything is working correctly, even though that's not what the test says it should be doing

2020-11-16 16:54 UTC, daniel112 commented on src/hooks/models/attendees/useIsAttendeeDisabledCallback.js
> +export const useIsAttendeeDisabledCallback = (session, attendees) => {
will continue in https://jira.simpleviewtools.com/browse/ZEN-458

2020-11-16 17:38 UTC, daniel112 approved these changes

2020-11-17 00:01 UTC, merged