Zen 419 booking context
simpleviewinc/tap-events-force pull request #95
Opened 2020-11-17 23:27 UTC by mpcarolin

**Ticket**: [ZEN-419](https://jira.simpleviewtools.com/browse/ZEN-419)

## Context

* the group booking modal needs to manage a lot of state specific to group booking, like the current booking list and the current capacity
* currently, this is stored in the global redux store, and managed by many hooks and actions. It's becoming hard to reason about.
* it would be simpler to manage the group booking state with a react context and a reducer. 

## Goal

* Refactor the group booking code to use react context rather than the redux store

## Updates

* `src/actions/session/booking/*`
  * removed several actions we no longer need
* `src/components/booking/attendeeBookingList.js` & `/attendeeCheckBoxItem.js`
  * updated to use the context state
  * simplified the code so that it wasn't calling `useMemo` in a loop
* `src/components/booking/groupBooker.js`
  * removed all initialization code that was happening in the function body through hooks
  * updated footer/header to use the context
* `src/components/booking/groupBookingSection.js`
  * updated jsdocs
* `src/components/modals/groupBooking.js`
  * updated to include the context provider here, to ensure it gets initialized before the body, header, or footer try to use it
  * also to be forward-compatible with Daniel's upcoming changes to the baseModal
* `src/constants/values.js`
  * removed constants we don't need any more
* `src/contexts/booking/groupBookingActionTypes.js`
  * some action type constants specific to the group booking context reducer
* `src/contexts/booking/groupBookingContext.js`
  * exporting the context and a helper hook to access it
* `src/contexts/booking/groupBookingInitialState.js`
  * exports the initial state of the group booking reducer
* `src/contexts/booking/groupBookingProvider.js`
  * the provider, which initializes the context state
  * also defines the reducer actions here
* `src/contexts/booking/groupBookingReducer.js`
  * reducer for handling state mutations
  * currently just handles the state change for updating the booking or waiting list with an attendee id (add or remove)
    * also handles updating the capacity and the "modified" properties
* `src/contexts/booking/useInitialState.js`
  * builds the initial state for the reducer
* `src/hooks/booking/useBookSessionCallback.js`
  * I removed the `useSessionBooking` hook, which did a number of things, and extracted this out of it.
  * this is all we need anymore: just returns the callback for booking a session
* `src/hooks/booking/*`
  * removed hooks we don't need anymore
* `src/hooks/booking/useBookingTimeConflicts.js`
  * linter's work
* `src/mocks/eventsforce/bookingStates/greaterCapacity.js`
  * just another test state for testing a session that is NOT unlimited, but has greater capacity than need.
  * access at: `?state=greaterCapacity.group.limited`
* `tap.js`
  * added an alias to the contexts folder, `SVContexts`

## Testing

`keg evf pack run ﻿﻿docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-419-booking-context`

* there are no new features, so we just need to test that the group booking modal works like it did before
* I went through and tested the instructions from this previous PR: https://github.com/simpleviewinc/tap-events-force/pull/63
  * however, the `/test` page doesn't exist anymore, so just use one of the test states, the existing sessions, or update the JSON to work as it describes
* to test the "Greater Capacity than Need" section, visit `?state=greaterCapacity.group.limited`

2020-11-18 20:01 UTC, daniel112 reviewed
still testing, but just want to post this comment first

2020-11-18 20:01 UTC, daniel112 commented on src/contexts/booking/groupBookingContext.js
> +export const useGroupBookingContext = () => useContext(GroupBookingContext)
no issue with this file specifically, I just want to make sure I understand fully.

from just looking at the structure. i was under the impression that `/contexts` contains only context + provider setup.
but it also contains hooks, initialState, actions and reducers.

was the intent just to group related functionality together in one module? 
the pattern just seems a bit weird and disconnected from the rest of our setup.

maybe this is just common context pattern? if so then i'm ok to go with it

2020-11-18 20:14 UTC, mpcarolin commented on src/contexts/booking/groupBookingActionTypes.js
> +export const GroupBookingActionTypes = {
I considered that, but these action types are only used in the `src/contexts/booking/*` files. They wouldn't be used elsewhere, and I didn't want them to be confused with the global redux action types. So I put them here. I'm open to changing that though.

2020-11-18 20:20 UTC, mpcarolin commented on src/contexts/booking/groupBookingContext.js
> +export const useGroupBookingContext = () => useContext(GroupBookingContext)
From my research, this is definitely a common react pattern. It's a reducer that is specific* to, and provided by, a single context, rather than globally accessible like redux. It seems disconnected because it it's supposed to.

*(yes, technically the context is global in the sense that any component _could_ import it, but that's discouraged, and since it only gets initialized when the group booking modal opens, it would be `undefined` for anyone who tries to access it outside of that window).

2020-11-18 21:22 UTC, daniel112 commented on src/contexts/booking/groupBookingActionTypes.js
> +export const GroupBookingActionTypes = {
there exists some constants thats currently being used for a single use case, so i think it's fine to put your constants in the `/constants` dir

if you want, we can make it more clear on the use case by putting your actionType under a `context` key.
so something like
`ActionTypes.CONTEXT.BOOKING.UPDATE_SESSION_BOOKING` or just `ActionTypes.CONTEXT.UPDATE_SESSION_BOOKING`

2020-11-18 21:25 UTC, daniel112 commented on src/contexts/booking/groupBookingContext.js
> +export const useGroupBookingContext = () => useContext(GroupBookingContext)
I don't have too strong of an opinion on this. but I think at the very least we should separate the different types of functions that you made under `contexts/booking` since not all of them are `context` or `provider`

after discussing further in chat. we want to ensure that the hooks and other utilities inside `contexts/booking` is only ever used within that context, so I'm okay with separating the hooks, actions, reducers inside the `contexts/booking` folder

```
   /context
     /booking
       /hooks
       /actions
       provider.js
       context.js
```

or something like that

2020-11-18 21:30 UTC, lancetipton requested changes
Looks really good. I like this so much more compared to before.
I left a few comments and questions. Thanks

2020-11-18 21:30 UTC, lancetipton commented on src/contexts/booking/useInitialState.js
> +import { initialState } from './groupBookingInitialState'
Normally I would be all for the name `useInitialState`, but since this is specific to booking, I think it would be important to state that. So I would update the name of this file to `useInitialBookingState`

2020-11-18 21:30 UTC, lancetipton commented on src/contexts/booking/groupBookingProvider.js
> +  const contextValue = useMemo(() => ({ state, actions }), [ state, actions ])
I'm not sure I understand why this is needed. 
* The state only updates from an action, so it's already memoized in a way, through the `useReducer` hook
* From my understanding, the actions will never change, because the dispatch will should never change.
  * See this [image](http://snpy.in/EljTt1) from the docs
    * Here's the [link](https://reactjs.org/docs/hooks-reference.html#usereducer) if you want to read more

Because the dispatch function never changes, it means there's no need to memorize the actions callback
Furthermore, because the state only changes from action calls, there's no need to memorize it either.

But there could be something I'm missing?

2020-11-18 21:30 UTC, lancetipton commented on src/contexts/booking/groupBookingReducer.js
> +  const [valid] = validate(
Not sure there's much point in doing this validation here
  * All calls to this method are done internally to this file, which means it's fully managed
  * It only really makes sense to use validation on the exported method in `groupBookingReducer` which calls `updateSessionBooking`
    * You are also doing validation there. And that makes more sense and provides value.
    * The validation here, I think is pointless

2020-11-18 21:34 UTC, lancetipton commented on src/contexts/booking/groupBookingActionTypes.js
> +export const GroupBookingActionTypes = {
Personally, I like the it seperated that way it is. 
The whole group booking section is basically it's own app.
Keeping it separated removes ambiguity, and ensures proper scoping.

That being said, if there are things that are shared it would make sense to join them together, but I don't think group booking actions is one of them.

Just my 2 cents

2020-11-18 21:35 UTC, lancetipton commented on src/contexts/booking/groupBookingContext.js
> +export const useGroupBookingContext = () => useContext(GroupBookingContext)
Nice, I'm glad ya'll came to this conclusion. Cause that's also what I would have recommended.

2020-11-18 22:27 UTC, lancetipton commented on src/contexts/booking/groupBookingProvider.js
> +  const contextValue = useMemo(() => ({ state, actions }), [ state, actions ])
After discussing this is slack, memoizing the state and actions as a single object makes sense.
This way they can be passed to value prop of the Context together.

2020-11-18 22:47 UTC, mpcarolin commented on src/contexts/booking/groupBookingReducer.js
> +  const [valid] = validate(
It was more intended to help me during development, as I was building this out. But it's served it's purpose so I'll go ahead and remove it.

2020-11-19 00:18 UTC, mpcarolin commented on src/contexts/booking/useInitialState.js
> +import { initialState } from './groupBookingInitialState'
yep agreed, updated

2020-11-19 00:18 UTC, mpcarolin commented on src/contexts/booking/groupBookingContext.js
> +export const useGroupBookingContext = () => useContext(GroupBookingContext)
updated with better folder structure

2020-11-19 16:21 UTC, daniel112 commented on src/contexts/booking/groupBookingReducer.js
> +  console.log(id)
can you remove this?

2020-11-19 16:24 UTC, daniel112 approved these changes
looks good. just 1 minor thing not blocking

2020-11-19 18:36 UTC, lancetipton requested changes
Looks good. I really like the folder structure, and everything is very clean. Great work
* Just one minor thing to look at. Thanks

2020-11-19 18:36 UTC, lancetipton commented on src/components/booking/groupBooker.js
> +    state.showCapacity && exists(state.capacity) && state.capacity !== Infinity
Pretty sure the first `state.showCapacity` is not needed here. Is there a reason for it?

2020-11-19 18:46 UTC, mpcarolin commented on src/components/booking/groupBooker.js
> +    state.showCapacity && exists(state.capacity) && state.capacity !== Infinity
I actually just added it to fix a bug I introduced with this refactor.

The spec actually requires the capacity count to be hidden if:
- the capacity is unlimited 

in which the session capacity isn't "unlimited", but it's still greater than the number of "bookable" attendees

2020-11-19 20:00 UTC, mpcarolin commented on src/contexts/booking/groupBookingReducer.js
> +  console.log(id)
thanks. updated

2020-11-19 20:41 UTC, lancetipton approved these changes
Great work. Looks good. Thanks

2020-11-19 21:51 UTC, merged